### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Navigation.ActionMode
  commentId: T:BindOpen.Application.Navigation.ActionMode
  id: ActionMode
  parent: BindOpen.Application.Navigation
  children:
  - BindOpen.Application.Navigation.ActionMode.Edition
  - BindOpen.Application.Navigation.ActionMode.Insertion
  - BindOpen.Application.Navigation.ActionMode.value__
  - BindOpen.Application.Navigation.ActionMode.View
  langs:
  - csharp
  - vb
  name: ActionMode
  nameWithType: ActionMode
  fullName: BindOpen.Application.Navigation.ActionMode
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nThis enumeration lists the possible modes of action.\n"
  syntax:
    content: 'public sealed class ActionMode : Enum'
    content.vb: >-
      Public NotInheritable Class ActionMode
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: BindOpen.Application.Navigation.ActionMode.value__
  commentId: F:BindOpen.Application.Navigation.ActionMode.value__
  id: value__
  parent: BindOpen.Application.Navigation.ActionMode
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: ActionMode.value__
  fullName: BindOpen.Application.Navigation.ActionMode.value__
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Navigation.ActionMode.View
  commentId: F:BindOpen.Application.Navigation.ActionMode.View
  id: View
  parent: BindOpen.Application.Navigation.ActionMode
  langs:
  - csharp
  - vb
  name: View
  nameWithType: ActionMode.View
  fullName: BindOpen.Application.Navigation.ActionMode.View
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nView.\n"
  syntax:
    content: public const ActionMode View
    return:
      type: BindOpen.Application.Navigation.ActionMode
    content.vb: Public Const View As ActionMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionMode.Insertion
  commentId: F:BindOpen.Application.Navigation.ActionMode.Insertion
  id: Insertion
  parent: BindOpen.Application.Navigation.ActionMode
  langs:
  - csharp
  - vb
  name: Insertion
  nameWithType: ActionMode.Insertion
  fullName: BindOpen.Application.Navigation.ActionMode.Insertion
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nInsertion.\n"
  syntax:
    content: public const ActionMode Insertion
    return:
      type: BindOpen.Application.Navigation.ActionMode
    content.vb: Public Const Insertion As ActionMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionMode.Edition
  commentId: F:BindOpen.Application.Navigation.ActionMode.Edition
  id: Edition
  parent: BindOpen.Application.Navigation.ActionMode
  langs:
  - csharp
  - vb
  name: Edition
  nameWithType: ActionMode.Edition
  fullName: BindOpen.Application.Navigation.ActionMode.Edition
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nEdition.\n"
  syntax:
    content: public const ActionMode Edition
    return:
      type: BindOpen.Application.Navigation.ActionMode
    content.vb: Public Const Edition As ActionMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BindOpen.Application.Navigation
  commentId: N:BindOpen.Application.Navigation
  isExternal: true
  name: BindOpen.Application.Navigation
  nameWithType: BindOpen.Application.Navigation
  fullName: BindOpen.Application.Navigation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: BindOpen.Application.Navigation.ActionMode
  commentId: T:BindOpen.Application.Navigation.ActionMode
  parent: BindOpen.Application.Navigation
  isExternal: true
  name: ActionMode
  nameWithType: ActionMode
  fullName: BindOpen.Application.Navigation.ActionMode
shouldSkipMarkup: true
