### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Services.IBdoHosted
  commentId: T:BindOpen.Application.Services.IBdoHosted
  id: IBdoHosted
  parent: BindOpen.Application.Services
  children:
  - BindOpen.Application.Services.IBdoHosted.Host
  langs:
  - csharp
  - vb
  name: IBdoHosted
  nameWithType: IBdoHosted
  fullName: BindOpen.Application.Services.IBdoHosted
  type: Interface
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nThe interface defines a hosted item.\n"
  syntax:
    content: public interface IBdoHosted
    content.vb: Public Interface IBdoHosted
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: BindOpen.Application.Services.IBdoHosted.Host
  commentId: P:BindOpen.Application.Services.IBdoHosted.Host
  id: Host
  parent: BindOpen.Application.Services.IBdoHosted
  langs:
  - csharp
  - vb
  name: Host
  nameWithType: IBdoHosted.Host
  fullName: BindOpen.Application.Services.IBdoHosted.Host
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nThe host of the instance.\n"
  syntax:
    content: IBdoHost Host { get; }
    parameters: []
    return:
      type: BindOpen.Application.Scopes.IBdoHost
    content.vb: ReadOnly Property Host As IBdoHost
  overload: BindOpen.Application.Services.IBdoHosted.Host*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: BindOpen.Application.Services
  commentId: N:BindOpen.Application.Services
  isExternal: true
  name: BindOpen.Application.Services
  nameWithType: BindOpen.Application.Services
  fullName: BindOpen.Application.Services
- uid: BindOpen.Application.Services.IBdoHosted.Host*
  commentId: Overload:BindOpen.Application.Services.IBdoHosted.Host
  isExternal: true
  name: Host
  nameWithType: IBdoHosted.Host
  fullName: BindOpen.Application.Services.IBdoHosted.Host
- uid: BindOpen.Application.Scopes.IBdoHost
  commentId: T:BindOpen.Application.Scopes.IBdoHost
  parent: BindOpen.Application.Scopes
  isExternal: true
  name: IBdoHost
  nameWithType: IBdoHost
  fullName: BindOpen.Application.Scopes.IBdoHost
- uid: BindOpen.Application.Scopes
  commentId: N:BindOpen.Application.Scopes
  isExternal: true
  name: BindOpen.Application.Scopes
  nameWithType: BindOpen.Application.Scopes
  fullName: BindOpen.Application.Scopes
shouldSkipMarkup: true
