### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Navigation.PageKind
  commentId: T:BindOpen.Application.Navigation.PageKind
  id: PageKind
  parent: BindOpen.Application.Navigation
  children:
  - BindOpen.Application.Navigation.PageKind.Default
  - BindOpen.Application.Navigation.PageKind.Home
  - BindOpen.Application.Navigation.PageKind.Login
  - BindOpen.Application.Navigation.PageKind.Main
  - BindOpen.Application.Navigation.PageKind.None
  - BindOpen.Application.Navigation.PageKind.Specified
  - BindOpen.Application.Navigation.PageKind.Standard
  - BindOpen.Application.Navigation.PageKind.value__
  langs:
  - csharp
  - vb
  name: PageKind
  nameWithType: PageKind
  fullName: BindOpen.Application.Navigation.PageKind
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nThis enumeration lists the possible kinds of pages.\n"
  syntax:
    content: 'public sealed class PageKind : Enum'
    content.vb: >-
      Public NotInheritable Class PageKind
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: BindOpen.Application.Navigation.PageKind.value__
  commentId: F:BindOpen.Application.Navigation.PageKind.value__
  id: value__
  parent: BindOpen.Application.Navigation.PageKind
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: PageKind.value__
  fullName: BindOpen.Application.Navigation.PageKind.value__
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Navigation.PageKind.None
  commentId: F:BindOpen.Application.Navigation.PageKind.None
  id: None
  parent: BindOpen.Application.Navigation.PageKind
  langs:
  - csharp
  - vb
  name: None
  nameWithType: PageKind.None
  fullName: BindOpen.Application.Navigation.PageKind.None
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nNone.\n"
  syntax:
    content: public const PageKind None
    return:
      type: BindOpen.Application.Navigation.PageKind
    content.vb: Public Const None As PageKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.PageKind.Standard
  commentId: F:BindOpen.Application.Navigation.PageKind.Standard
  id: Standard
  parent: BindOpen.Application.Navigation.PageKind
  langs:
  - csharp
  - vb
  name: Standard
  nameWithType: PageKind.Standard
  fullName: BindOpen.Application.Navigation.PageKind.Standard
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nStandard.\n"
  syntax:
    content: public const PageKind Standard
    return:
      type: BindOpen.Application.Navigation.PageKind
    content.vb: Public Const Standard As PageKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.PageKind.Default
  commentId: F:BindOpen.Application.Navigation.PageKind.Default
  id: Default
  parent: BindOpen.Application.Navigation.PageKind
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: PageKind.Default
  fullName: BindOpen.Application.Navigation.PageKind.Default
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nDefault page.\n"
  syntax:
    content: public const PageKind Default
    return:
      type: BindOpen.Application.Navigation.PageKind
    content.vb: Public Const Default As PageKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.PageKind.Main
  commentId: F:BindOpen.Application.Navigation.PageKind.Main
  id: Main
  parent: BindOpen.Application.Navigation.PageKind
  langs:
  - csharp
  - vb
  name: Main
  nameWithType: PageKind.Main
  fullName: BindOpen.Application.Navigation.PageKind.Main
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nMain page.\n"
  syntax:
    content: public const PageKind Main
    return:
      type: BindOpen.Application.Navigation.PageKind
    content.vb: Public Const Main As PageKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.PageKind.Login
  commentId: F:BindOpen.Application.Navigation.PageKind.Login
  id: Login
  parent: BindOpen.Application.Navigation.PageKind
  langs:
  - csharp
  - vb
  name: Login
  nameWithType: PageKind.Login
  fullName: BindOpen.Application.Navigation.PageKind.Login
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nLogin page.\n"
  syntax:
    content: public const PageKind Login
    return:
      type: BindOpen.Application.Navigation.PageKind
    content.vb: Public Const Login As PageKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.PageKind.Home
  commentId: F:BindOpen.Application.Navigation.PageKind.Home
  id: Home
  parent: BindOpen.Application.Navigation.PageKind
  langs:
  - csharp
  - vb
  name: Home
  nameWithType: PageKind.Home
  fullName: BindOpen.Application.Navigation.PageKind.Home
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nHome page.\n"
  syntax:
    content: public const PageKind Home
    return:
      type: BindOpen.Application.Navigation.PageKind
    content.vb: Public Const Home As PageKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.PageKind.Specified
  commentId: F:BindOpen.Application.Navigation.PageKind.Specified
  id: Specified
  parent: BindOpen.Application.Navigation.PageKind
  langs:
  - csharp
  - vb
  name: Specified
  nameWithType: PageKind.Specified
  fullName: BindOpen.Application.Navigation.PageKind.Specified
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nSpecified page.\n"
  syntax:
    content: public const PageKind Specified
    return:
      type: BindOpen.Application.Navigation.PageKind
    content.vb: Public Const Specified As PageKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BindOpen.Application.Navigation
  commentId: N:BindOpen.Application.Navigation
  isExternal: true
  name: BindOpen.Application.Navigation
  nameWithType: BindOpen.Application.Navigation
  fullName: BindOpen.Application.Navigation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: BindOpen.Application.Navigation.PageKind
  commentId: T:BindOpen.Application.Navigation.PageKind
  parent: BindOpen.Application.Navigation
  isExternal: true
  name: PageKind
  nameWithType: PageKind
  fullName: BindOpen.Application.Navigation.PageKind
shouldSkipMarkup: true
