### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  commentId: T:BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  id: ProductInformation.ProductAffiliateNetwork
  parent: BindOpen.Application.Products
  children:
  - BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.MyCommerce
  - BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.None
  - BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.value__
  langs:
  - csharp
  - vb
  name: ProductInformation.ProductAffiliateNetwork
  nameWithType: ProductInformation.ProductAffiliateNetwork
  fullName: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  summary: "\nThis enumeration lists all the possible product affiliate network.\n"
  syntax:
    content: 'public sealed class ProductAffiliateNetwork : Enum'
    content.vb: >-
      Public NotInheritable Class ProductAffiliateNetwork
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.value__
  commentId: F:BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.value__
  id: value__
  parent: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: ProductInformation.ProductAffiliateNetwork.value__
  fullName: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.value__
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.None
  commentId: F:BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.None
  id: None
  parent: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ProductInformation.ProductAffiliateNetwork.None
  fullName: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.None
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  summary: "\nNone\n"
  syntax:
    content: public const ProductInformation.ProductAffiliateNetwork None
    return:
      type: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
    content.vb: Public Const None As ProductInformation.ProductAffiliateNetwork
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.MyCommerce
  commentId: F:BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.MyCommerce
  id: MyCommerce
  parent: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  langs:
  - csharp
  - vb
  name: MyCommerce
  nameWithType: ProductInformation.ProductAffiliateNetwork.MyCommerce
  fullName: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork.MyCommerce
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  summary: "\nMyCommerce\n"
  syntax:
    content: public const ProductInformation.ProductAffiliateNetwork MyCommerce
    return:
      type: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
    content.vb: Public Const MyCommerce As ProductInformation.ProductAffiliateNetwork
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BindOpen.Application.Products
  commentId: N:BindOpen.Application.Products
  isExternal: true
  name: BindOpen.Application.Products
  nameWithType: BindOpen.Application.Products
  fullName: BindOpen.Application.Products
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  commentId: T:BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  parent: BindOpen.Application.Products
  isExternal: true
  name: ProductInformation.ProductAffiliateNetwork
  nameWithType: ProductInformation.ProductAffiliateNetwork
  fullName: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
shouldSkipMarkup: true
