### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths
  commentId: T:BindOpen.Application.Scopes.BdoDefaultHostPaths
  id: BdoDefaultHostPaths
  parent: BindOpen.Application.Scopes
  children:
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultAppConfigFileName
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultAppConfigFolderPath
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultHostConfigFileName
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLibraryFolderPath
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLogsFileName
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLogsFolderPath
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultPackagesFolderPath
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultPrimaryLogsFileNamePreffix
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultProjectsFolderPath
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultRootFolderPath
  - BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultRuntimeFolderPath
  - BindOpen.Application.Scopes.BdoDefaultHostPaths._AUTHENTICATIONTIMEOUT
  langs:
  - csharp
  - vb
  name: BdoDefaultHostPaths
  nameWithType: BdoDefaultHostPaths
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThis static class contains the default option values.\n"
  syntax:
    content: 'public static class BdoDefaultHostPaths : Object'
    content.vb: >-
      Public Module BdoDefaultHostPaths
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultRootFolderPath
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultRootFolderPath
  id: __DefaultRootFolderPath
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultRootFolderPath
  nameWithType: BdoDefaultHostPaths.__DefaultRootFolderPath
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultRootFolderPath
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default root folder\n"
  syntax:
    content: public static readonly string __DefaultRootFolderPath
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultRootFolderPath As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultHostConfigFileName
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultHostConfigFileName
  id: __DefaultHostConfigFileName
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultHostConfigFileName
  nameWithType: BdoDefaultHostPaths.__DefaultHostConfigFileName
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultHostConfigFileName
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default host settings file name\n"
  syntax:
    content: public static readonly string __DefaultHostConfigFileName
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultHostConfigFileName As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultAppConfigFileName
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultAppConfigFileName
  id: __DefaultAppConfigFileName
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultAppConfigFileName
  nameWithType: BdoDefaultHostPaths.__DefaultAppConfigFileName
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultAppConfigFileName
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default application configuration file name\n"
  syntax:
    content: public static readonly string __DefaultAppConfigFileName
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultAppConfigFileName As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultRuntimeFolderPath
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultRuntimeFolderPath
  id: __DefaultRuntimeFolderPath
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultRuntimeFolderPath
  nameWithType: BdoDefaultHostPaths.__DefaultRuntimeFolderPath
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultRuntimeFolderPath
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default runtime folder path.\n"
  syntax:
    content: public static readonly string __DefaultRuntimeFolderPath
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultRuntimeFolderPath As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultAppConfigFolderPath
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultAppConfigFolderPath
  id: __DefaultAppConfigFolderPath
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultAppConfigFolderPath
  nameWithType: BdoDefaultHostPaths.__DefaultAppConfigFolderPath
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultAppConfigFolderPath
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default settings folder path.\n"
  syntax:
    content: public static readonly string __DefaultAppConfigFolderPath
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultAppConfigFolderPath As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLogsFolderPath
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLogsFolderPath
  id: __DefaultLogsFolderPath
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultLogsFolderPath
  nameWithType: BdoDefaultHostPaths.__DefaultLogsFolderPath
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLogsFolderPath
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default logs folder path.\n"
  syntax:
    content: public static readonly string __DefaultLogsFolderPath
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultLogsFolderPath As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLibraryFolderPath
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLibraryFolderPath
  id: __DefaultLibraryFolderPath
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultLibraryFolderPath
  nameWithType: BdoDefaultHostPaths.__DefaultLibraryFolderPath
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLibraryFolderPath
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default library folder path.\n"
  syntax:
    content: public static readonly string __DefaultLibraryFolderPath
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultLibraryFolderPath As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultPackagesFolderPath
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultPackagesFolderPath
  id: __DefaultPackagesFolderPath
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultPackagesFolderPath
  nameWithType: BdoDefaultHostPaths.__DefaultPackagesFolderPath
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultPackagesFolderPath
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default packages folder path.\n"
  syntax:
    content: public static readonly string __DefaultPackagesFolderPath
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultPackagesFolderPath As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultProjectsFolderPath
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultProjectsFolderPath
  id: __DefaultProjectsFolderPath
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultProjectsFolderPath
  nameWithType: BdoDefaultHostPaths.__DefaultProjectsFolderPath
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultProjectsFolderPath
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default projects folder path.\n"
  syntax:
    content: public static readonly string __DefaultProjectsFolderPath
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultProjectsFolderPath As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLogsFileName
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLogsFileName
  id: __DefaultLogsFileName
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultLogsFileName
  nameWithType: BdoDefaultHostPaths.__DefaultLogsFileName
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultLogsFileName
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe default log file name.\n"
  syntax:
    content: public static readonly string __DefaultLogsFileName
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultLogsFileName As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultPrimaryLogsFileNamePreffix
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultPrimaryLogsFileNamePreffix
  id: __DefaultPrimaryLogsFileNamePreffix
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: __DefaultPrimaryLogsFileNamePreffix
  nameWithType: BdoDefaultHostPaths.__DefaultPrimaryLogsFileNamePreffix
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths.__DefaultPrimaryLogsFileNamePreffix
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nThe preffix of the default primary logs file name.\n"
  syntax:
    content: public static readonly string __DefaultPrimaryLogsFileNamePreffix
    return:
      type: System.String
    content.vb: Public Shared ReadOnly __DefaultPrimaryLogsFileNamePreffix As String
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: BindOpen.Application.Scopes.BdoDefaultHostPaths._AUTHENTICATIONTIMEOUT
  commentId: F:BindOpen.Application.Scopes.BdoDefaultHostPaths._AUTHENTICATIONTIMEOUT
  id: _AUTHENTICATIONTIMEOUT
  parent: BindOpen.Application.Scopes.BdoDefaultHostPaths
  langs:
  - csharp
  - vb
  name: _AUTHENTICATIONTIMEOUT
  nameWithType: BdoDefaultHostPaths._AUTHENTICATIONTIMEOUT
  fullName: BindOpen.Application.Scopes.BdoDefaultHostPaths._AUTHENTICATIONTIMEOUT
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Scopes
  summary: "\nMaximum number of minutes : authentication \n"
  syntax:
    content: public static readonly int _AUTHENTICATIONTIMEOUT
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly _AUTHENTICATIONTIMEOUT As Integer
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: BindOpen.Application.Scopes
  commentId: N:BindOpen.Application.Scopes
  isExternal: true
  name: BindOpen.Application.Scopes
  nameWithType: BindOpen.Application.Scopes
  fullName: BindOpen.Application.Scopes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
shouldSkipMarkup: true
