### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Languages.ApplicationLanguage
  commentId: T:BindOpen.Application.Languages.ApplicationLanguage
  id: ApplicationLanguage
  parent: BindOpen.Application.Languages
  children:
  - BindOpen.Application.Languages.ApplicationLanguage.#ctor
  - BindOpen.Application.Languages.ApplicationLanguage.CultureName
  - BindOpen.Application.Languages.ApplicationLanguage.UICultureName
  langs:
  - csharp
  - vb
  name: ApplicationLanguage
  nameWithType: ApplicationLanguage
  fullName: BindOpen.Application.Languages.ApplicationLanguage
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Languages
  summary: "\nThis class represents a application languages.\n"
  syntax:
    content: 'public class ApplicationLanguage : DescribedDataItem, IApplicationLanguage, IDescribedDataItem, ITitledDataItem, INamedDataItem, IStoredDataItem, IIdentifiedDataItem, IDataItem, ICloneable, IDisposable, IIdentified, IReferenced, IStorable, INamed, IGloballyTitled, IGloballyDescribed'
    content.vb: >-
      Public Class ApplicationLanguage
          Inherits DescribedDataItem
          Implements IApplicationLanguage, IDescribedDataItem, ITitledDataItem, INamedDataItem, IStoredDataItem, IIdentifiedDataItem, IDataItem, ICloneable, IDisposable, IIdentified, IReferenced, IStorable, INamed, IGloballyTitled, IGloballyDescribed
  inheritance:
  - System.Object
  implements:
  - BindOpen.Application.Languages.IApplicationLanguage
  - BindOpen.Data.Items.IDescribedDataItem
  - BindOpen.Data.Items.ITitledDataItem
  - BindOpen.Data.Items.INamedDataItem
  - BindOpen.Data.Items.IStoredDataItem
  - BindOpen.Data.Items.IIdentifiedDataItem
  - BindOpen.Data.Items.IDataItem
  - System.ICloneable
  - System.IDisposable
  - BindOpen.Data.Items.IIdentified
  - BindOpen.Data.Items.IReferenced
  - BindOpen.Data.Items.IStorable
  - BindOpen.Data.Items.INamed
  - BindOpen.Data.Items.IGloballyTitled
  - BindOpen.Data.Items.IGloballyDescribed
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: BindOpen.Application.Languages.ApplicationLanguage.#ctor
  commentId: M:BindOpen.Application.Languages.ApplicationLanguage.#ctor
  id: '#ctor'
  parent: BindOpen.Application.Languages.ApplicationLanguage
  langs:
  - csharp
  - vb
  name: ApplicationLanguage()
  nameWithType: ApplicationLanguage.ApplicationLanguage()
  fullName: BindOpen.Application.Languages.ApplicationLanguage.ApplicationLanguage()
  type: Constructor
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Languages
  summary: "\nInstantiates a new instance of ApplicationLanguage class.\n"
  syntax:
    content: public ApplicationLanguage()
    content.vb: Public Sub New
  overload: BindOpen.Application.Languages.ApplicationLanguage.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Languages.ApplicationLanguage.UICultureName
  commentId: P:BindOpen.Application.Languages.ApplicationLanguage.UICultureName
  id: UICultureName
  parent: BindOpen.Application.Languages.ApplicationLanguage
  langs:
  - csharp
  - vb
  name: UICultureName
  nameWithType: ApplicationLanguage.UICultureName
  fullName: BindOpen.Application.Languages.ApplicationLanguage.UICultureName
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Languages
  summary: "\nThe UI culture of this instance.\n"
  syntax:
    content: public string UICultureName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property UICultureName As String
  overload: BindOpen.Application.Languages.ApplicationLanguage.UICultureName*
  implements:
  - BindOpen.Application.Languages.IApplicationLanguage.UICultureName
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Languages.ApplicationLanguage.CultureName
  commentId: P:BindOpen.Application.Languages.ApplicationLanguage.CultureName
  id: CultureName
  parent: BindOpen.Application.Languages.ApplicationLanguage
  langs:
  - csharp
  - vb
  name: CultureName
  nameWithType: ApplicationLanguage.CultureName
  fullName: BindOpen.Application.Languages.ApplicationLanguage.CultureName
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Languages
  summary: "\nThe culture name of this instance.\n"
  syntax:
    content: public string CultureName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property CultureName As String
  overload: BindOpen.Application.Languages.ApplicationLanguage.CultureName*
  implements:
  - BindOpen.Application.Languages.IApplicationLanguage.CultureName
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: BindOpen.Application.Languages
  commentId: N:BindOpen.Application.Languages
  isExternal: true
  name: BindOpen.Application.Languages
  nameWithType: BindOpen.Application.Languages
  fullName: BindOpen.Application.Languages
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: BindOpen.Application.Languages.IApplicationLanguage
  commentId: T:BindOpen.Application.Languages.IApplicationLanguage
  parent: BindOpen.Application.Languages
  isExternal: true
  name: IApplicationLanguage
  nameWithType: IApplicationLanguage
  fullName: BindOpen.Application.Languages.IApplicationLanguage
- uid: BindOpen.Data.Items.IDescribedDataItem
  isExternal: true
  name: IDescribedDataItem
  nameWithType: IDescribedDataItem
  fullName: BindOpen.Data.Items.IDescribedDataItem
- uid: BindOpen.Data.Items.ITitledDataItem
  isExternal: true
  name: ITitledDataItem
  nameWithType: ITitledDataItem
  fullName: BindOpen.Data.Items.ITitledDataItem
- uid: BindOpen.Data.Items.INamedDataItem
  isExternal: true
  name: INamedDataItem
  nameWithType: INamedDataItem
  fullName: BindOpen.Data.Items.INamedDataItem
- uid: BindOpen.Data.Items.IStoredDataItem
  isExternal: true
  name: IStoredDataItem
  nameWithType: IStoredDataItem
  fullName: BindOpen.Data.Items.IStoredDataItem
- uid: BindOpen.Data.Items.IIdentifiedDataItem
  isExternal: true
  name: IIdentifiedDataItem
  nameWithType: IIdentifiedDataItem
  fullName: BindOpen.Data.Items.IIdentifiedDataItem
- uid: BindOpen.Data.Items.IDataItem
  isExternal: true
  name: IDataItem
  nameWithType: IDataItem
  fullName: BindOpen.Data.Items.IDataItem
- uid: System.ICloneable
  isExternal: true
  name: ICloneable
  nameWithType: ICloneable
  fullName: System.ICloneable
- uid: System.IDisposable
  isExternal: true
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: BindOpen.Data.Items.IIdentified
  isExternal: true
  name: IIdentified
  nameWithType: IIdentified
  fullName: BindOpen.Data.Items.IIdentified
- uid: BindOpen.Data.Items.IReferenced
  isExternal: true
  name: IReferenced
  nameWithType: IReferenced
  fullName: BindOpen.Data.Items.IReferenced
- uid: BindOpen.Data.Items.IStorable
  isExternal: true
  name: IStorable
  nameWithType: IStorable
  fullName: BindOpen.Data.Items.IStorable
- uid: BindOpen.Data.Items.INamed
  isExternal: true
  name: INamed
  nameWithType: INamed
  fullName: BindOpen.Data.Items.INamed
- uid: BindOpen.Data.Items.IGloballyTitled
  isExternal: true
  name: IGloballyTitled
  nameWithType: IGloballyTitled
  fullName: BindOpen.Data.Items.IGloballyTitled
- uid: BindOpen.Data.Items.IGloballyDescribed
  isExternal: true
  name: IGloballyDescribed
  nameWithType: IGloballyDescribed
  fullName: BindOpen.Data.Items.IGloballyDescribed
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: BindOpen.Application.Languages.ApplicationLanguage.#ctor*
  commentId: Overload:BindOpen.Application.Languages.ApplicationLanguage.#ctor
  isExternal: true
  name: ApplicationLanguage
  nameWithType: ApplicationLanguage.ApplicationLanguage
  fullName: BindOpen.Application.Languages.ApplicationLanguage.ApplicationLanguage
- uid: BindOpen.Application.Languages.ApplicationLanguage.UICultureName*
  commentId: Overload:BindOpen.Application.Languages.ApplicationLanguage.UICultureName
  isExternal: true
  name: UICultureName
  nameWithType: ApplicationLanguage.UICultureName
  fullName: BindOpen.Application.Languages.ApplicationLanguage.UICultureName
- uid: BindOpen.Application.Languages.IApplicationLanguage.UICultureName
  commentId: P:BindOpen.Application.Languages.IApplicationLanguage.UICultureName
  parent: BindOpen.Application.Languages.IApplicationLanguage
  isExternal: true
  name: UICultureName
  nameWithType: IApplicationLanguage.UICultureName
  fullName: BindOpen.Application.Languages.IApplicationLanguage.UICultureName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: BindOpen.Application.Languages.ApplicationLanguage.CultureName*
  commentId: Overload:BindOpen.Application.Languages.ApplicationLanguage.CultureName
  isExternal: true
  name: CultureName
  nameWithType: ApplicationLanguage.CultureName
  fullName: BindOpen.Application.Languages.ApplicationLanguage.CultureName
- uid: BindOpen.Application.Languages.IApplicationLanguage.CultureName
  commentId: P:BindOpen.Application.Languages.IApplicationLanguage.CultureName
  parent: BindOpen.Application.Languages.IApplicationLanguage
  isExternal: true
  name: CultureName
  nameWithType: IApplicationLanguage.CultureName
  fullName: BindOpen.Application.Languages.IApplicationLanguage.CultureName
shouldSkipMarkup: true
