### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Messages.DisplayMessage
  commentId: T:BindOpen.Application.Messages.DisplayMessage
  id: DisplayMessage
  parent: BindOpen.Application.Messages
  children:
  - BindOpen.Application.Messages.DisplayMessage.#ctor
  - BindOpen.Application.Messages.DisplayMessage.CanBeHidden
  - BindOpen.Application.Messages.DisplayMessage.Clone
  - BindOpen.Application.Messages.DisplayMessage.DisplayCondition
  - BindOpen.Application.Messages.DisplayMessage.DisplayedLabel
  - BindOpen.Application.Messages.DisplayMessage.DisplayOption
  - BindOpen.Application.Messages.DisplayMessage.IsAutomaticRedirection
  - BindOpen.Application.Messages.DisplayMessage.Kind
  - BindOpen.Application.Messages.DisplayMessage.LinkUri
  langs:
  - csharp
  - vb
  name: DisplayMessage
  nameWithType: DisplayMessage
  fullName: BindOpen.Application.Messages.DisplayMessage
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nThis structure respresents a display message.\n"
  syntax:
    content: 'public class DisplayMessage : StoredDataItem'
    content.vb: >-
      Public Class DisplayMessage
          Inherits StoredDataItem
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: BindOpen.Application.Messages.DisplayMessage.#ctor
  commentId: M:BindOpen.Application.Messages.DisplayMessage.#ctor
  id: '#ctor'
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: DisplayMessage()
  nameWithType: DisplayMessage.DisplayMessage()
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayMessage()
  type: Constructor
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nCreates a new instance of the DisplayMessage class.\n"
  syntax:
    content: public DisplayMessage()
    content.vb: Public Sub New
  overload: BindOpen.Application.Messages.DisplayMessage.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Messages.DisplayMessage.Clone
  commentId: M:BindOpen.Application.Messages.DisplayMessage.Clone
  id: Clone
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: Clone()
  nameWithType: DisplayMessage.Clone()
  fullName: BindOpen.Application.Messages.DisplayMessage.Clone()
  type: Method
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nClones this instance.\n"
  syntax:
    content: public override object Clone()
    return:
      type: System.Object
    content.vb: Public Overrides Function Clone As Object
  overload: BindOpen.Application.Messages.DisplayMessage.Clone*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: BindOpen.Application.Messages.DisplayMessage.DisplayCondition
  commentId: P:BindOpen.Application.Messages.DisplayMessage.DisplayCondition
  id: DisplayCondition
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: DisplayCondition
  nameWithType: DisplayMessage.DisplayCondition
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayCondition
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nDisplay condition of this instance.\n"
  syntax:
    content: public ScriptCondition DisplayCondition { get; set; }
    parameters: []
    return:
      type: BindOpen.Data.Conditions.ScriptCondition
    content.vb: Public Property DisplayCondition As ScriptCondition
  overload: BindOpen.Application.Messages.DisplayMessage.DisplayCondition*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Messages.DisplayMessage.DisplayedLabel
  commentId: P:BindOpen.Application.Messages.DisplayMessage.DisplayedLabel
  id: DisplayedLabel
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: DisplayedLabel
  nameWithType: DisplayMessage.DisplayedLabel
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayedLabel
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nDisplayed label of this instance.\n"
  syntax:
    content: public DictionaryDataItem DisplayedLabel { get; set; }
    parameters: []
    return:
      type: BindOpen.Data.Items.DictionaryDataItem
    content.vb: Public Property DisplayedLabel As DictionaryDataItem
  overload: BindOpen.Application.Messages.DisplayMessage.DisplayedLabel*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Messages.DisplayMessage.LinkUri
  commentId: P:BindOpen.Application.Messages.DisplayMessage.LinkUri
  id: LinkUri
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: LinkUri
  nameWithType: DisplayMessage.LinkUri
  fullName: BindOpen.Application.Messages.DisplayMessage.LinkUri
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nLink URI of this instance.\n"
  syntax:
    content: public string LinkUri { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LinkUri As String
  overload: BindOpen.Application.Messages.DisplayMessage.LinkUri*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Messages.DisplayMessage.DisplayOption
  commentId: P:BindOpen.Application.Messages.DisplayMessage.DisplayOption
  id: DisplayOption
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: DisplayOption
  nameWithType: DisplayMessage.DisplayOption
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayOption
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nDisplay option of this instance.\n"
  syntax:
    content: public DisplayMessage.DisplayMessageOption DisplayOption { get; set; }
    parameters: []
    return:
      type: BindOpen.Application.Messages.DisplayMessage.DisplayMessageOption
    content.vb: Public Property DisplayOption As DisplayMessage.DisplayMessageOption
  overload: BindOpen.Application.Messages.DisplayMessage.DisplayOption*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Messages.DisplayMessage.Kind
  commentId: P:BindOpen.Application.Messages.DisplayMessage.Kind
  id: Kind
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: Kind
  nameWithType: DisplayMessage.Kind
  fullName: BindOpen.Application.Messages.DisplayMessage.Kind
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nKind of this instance.\n"
  syntax:
    content: public EventKinds Kind { get; set; }
    parameters: []
    return:
      type: BindOpen.System.Diagnostics.Events.EventKinds
    content.vb: Public Property Kind As EventKinds
  overload: BindOpen.Application.Messages.DisplayMessage.Kind*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Messages.DisplayMessage.CanBeHidden
  commentId: P:BindOpen.Application.Messages.DisplayMessage.CanBeHidden
  id: CanBeHidden
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: CanBeHidden
  nameWithType: DisplayMessage.CanBeHidden
  fullName: BindOpen.Application.Messages.DisplayMessage.CanBeHidden
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nIndicates whether this instance can be hidden.\n"
  syntax:
    content: public bool CanBeHidden { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property CanBeHidden As Boolean
  overload: BindOpen.Application.Messages.DisplayMessage.CanBeHidden*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Messages.DisplayMessage.IsAutomaticRedirection
  commentId: P:BindOpen.Application.Messages.DisplayMessage.IsAutomaticRedirection
  id: IsAutomaticRedirection
  parent: BindOpen.Application.Messages.DisplayMessage
  langs:
  - csharp
  - vb
  name: IsAutomaticRedirection
  nameWithType: DisplayMessage.IsAutomaticRedirection
  fullName: BindOpen.Application.Messages.DisplayMessage.IsAutomaticRedirection
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Messages
  summary: "\nIndicates whether the redirection of this instance is automatic.\n"
  syntax:
    content: public bool IsAutomaticRedirection { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsAutomaticRedirection As Boolean
  overload: BindOpen.Application.Messages.DisplayMessage.IsAutomaticRedirection*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: BindOpen.Application.Messages
  commentId: N:BindOpen.Application.Messages
  isExternal: true
  name: BindOpen.Application.Messages
  nameWithType: BindOpen.Application.Messages
  fullName: BindOpen.Application.Messages
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: BindOpen.Application.Messages.DisplayMessage.#ctor*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.#ctor
  isExternal: true
  name: DisplayMessage
  nameWithType: DisplayMessage.DisplayMessage
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayMessage
- uid: BindOpen.Application.Messages.DisplayMessage.Clone*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.Clone
  isExternal: true
  name: Clone
  nameWithType: DisplayMessage.Clone
  fullName: BindOpen.Application.Messages.DisplayMessage.Clone
- uid: BindOpen.Application.Messages.DisplayMessage.DisplayCondition*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.DisplayCondition
  isExternal: true
  name: DisplayCondition
  nameWithType: DisplayMessage.DisplayCondition
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayCondition
- uid: BindOpen.Data.Conditions.ScriptCondition
  commentId: '!:BindOpen.Data.Conditions.ScriptCondition'
  isExternal: true
  name: ScriptCondition
  nameWithType: ScriptCondition
  fullName: BindOpen.Data.Conditions.ScriptCondition
- uid: BindOpen.Application.Messages.DisplayMessage.DisplayedLabel*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.DisplayedLabel
  isExternal: true
  name: DisplayedLabel
  nameWithType: DisplayMessage.DisplayedLabel
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayedLabel
- uid: BindOpen.Data.Items.DictionaryDataItem
  isExternal: true
  name: DictionaryDataItem
  nameWithType: DictionaryDataItem
  fullName: BindOpen.Data.Items.DictionaryDataItem
- uid: BindOpen.Application.Messages.DisplayMessage.LinkUri*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.LinkUri
  isExternal: true
  name: LinkUri
  nameWithType: DisplayMessage.LinkUri
  fullName: BindOpen.Application.Messages.DisplayMessage.LinkUri
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: BindOpen.Application.Messages.DisplayMessage.DisplayOption*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.DisplayOption
  isExternal: true
  name: DisplayOption
  nameWithType: DisplayMessage.DisplayOption
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayOption
- uid: BindOpen.Application.Messages.DisplayMessage.DisplayMessageOption
  commentId: T:BindOpen.Application.Messages.DisplayMessage.DisplayMessageOption
  parent: BindOpen.Application.Messages
  isExternal: true
  name: DisplayMessage.DisplayMessageOption
  nameWithType: DisplayMessage.DisplayMessageOption
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayMessageOption
- uid: BindOpen.Application.Messages.DisplayMessage.Kind*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.Kind
  isExternal: true
  name: Kind
  nameWithType: DisplayMessage.Kind
  fullName: BindOpen.Application.Messages.DisplayMessage.Kind
- uid: BindOpen.System.Diagnostics.Events.EventKinds
  commentId: '!:BindOpen.System.Diagnostics.Events.EventKinds'
  isExternal: true
  name: EventKinds
  nameWithType: EventKinds
  fullName: BindOpen.System.Diagnostics.Events.EventKinds
- uid: BindOpen.Application.Messages.DisplayMessage.CanBeHidden*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.CanBeHidden
  isExternal: true
  name: CanBeHidden
  nameWithType: DisplayMessage.CanBeHidden
  fullName: BindOpen.Application.Messages.DisplayMessage.CanBeHidden
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: BindOpen.Application.Messages.DisplayMessage.IsAutomaticRedirection*
  commentId: Overload:BindOpen.Application.Messages.DisplayMessage.IsAutomaticRedirection
  isExternal: true
  name: IsAutomaticRedirection
  nameWithType: DisplayMessage.IsAutomaticRedirection
  fullName: BindOpen.Application.Messages.DisplayMessage.IsAutomaticRedirection
shouldSkipMarkup: true
