### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Products.ProductRegistrationMode
  commentId: T:BindOpen.Application.Products.ProductRegistrationMode
  id: ProductRegistrationMode
  parent: BindOpen.Application.Products
  children:
  - BindOpen.Application.Products.ProductRegistrationMode.Any
  - BindOpen.Application.Products.ProductRegistrationMode.Registered
  - BindOpen.Application.Products.ProductRegistrationMode.Unregistered
  - BindOpen.Application.Products.ProductRegistrationMode.value__
  langs:
  - csharp
  - vb
  name: ProductRegistrationMode
  nameWithType: ProductRegistrationMode
  fullName: BindOpen.Application.Products.ProductRegistrationMode
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  summary: "\nThis enumerates the possible modes of product registration.\n"
  syntax:
    content: 'public sealed class ProductRegistrationMode : Enum'
    content.vb: >-
      Public NotInheritable Class ProductRegistrationMode
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: BindOpen.Application.Products.ProductRegistrationMode.value__
  commentId: F:BindOpen.Application.Products.ProductRegistrationMode.value__
  id: value__
  parent: BindOpen.Application.Products.ProductRegistrationMode
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: ProductRegistrationMode.value__
  fullName: BindOpen.Application.Products.ProductRegistrationMode.value__
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Products.ProductRegistrationMode.Any
  commentId: F:BindOpen.Application.Products.ProductRegistrationMode.Any
  id: Any
  parent: BindOpen.Application.Products.ProductRegistrationMode
  langs:
  - csharp
  - vb
  name: Any
  nameWithType: ProductRegistrationMode.Any
  fullName: BindOpen.Application.Products.ProductRegistrationMode.Any
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  summary: "\nAny.\n"
  syntax:
    content: public const ProductRegistrationMode Any
    return:
      type: BindOpen.Application.Products.ProductRegistrationMode
    content.vb: Public Const Any As ProductRegistrationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Products.ProductRegistrationMode.Registered
  commentId: F:BindOpen.Application.Products.ProductRegistrationMode.Registered
  id: Registered
  parent: BindOpen.Application.Products.ProductRegistrationMode
  langs:
  - csharp
  - vb
  name: Registered
  nameWithType: ProductRegistrationMode.Registered
  fullName: BindOpen.Application.Products.ProductRegistrationMode.Registered
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  summary: "\nRegistered.\n"
  syntax:
    content: public const ProductRegistrationMode Registered
    return:
      type: BindOpen.Application.Products.ProductRegistrationMode
    content.vb: Public Const Registered As ProductRegistrationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Products.ProductRegistrationMode.Unregistered
  commentId: F:BindOpen.Application.Products.ProductRegistrationMode.Unregistered
  id: Unregistered
  parent: BindOpen.Application.Products.ProductRegistrationMode
  langs:
  - csharp
  - vb
  name: Unregistered
  nameWithType: ProductRegistrationMode.Unregistered
  fullName: BindOpen.Application.Products.ProductRegistrationMode.Unregistered
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Products
  summary: "\nUnregistered.\n"
  syntax:
    content: public const ProductRegistrationMode Unregistered
    return:
      type: BindOpen.Application.Products.ProductRegistrationMode
    content.vb: Public Const Unregistered As ProductRegistrationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BindOpen.Application.Products
  commentId: N:BindOpen.Application.Products
  isExternal: true
  name: BindOpen.Application.Products
  nameWithType: BindOpen.Application.Products
  fullName: BindOpen.Application.Products
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: BindOpen.Application.Products.ProductRegistrationMode
  commentId: T:BindOpen.Application.Products.ProductRegistrationMode
  parent: BindOpen.Application.Products
  isExternal: true
  name: ProductRegistrationMode
  nameWithType: ProductRegistrationMode
  fullName: BindOpen.Application.Products.ProductRegistrationMode
shouldSkipMarkup: true
