### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Configuration.BdoHostConfiguration
  commentId: T:BindOpen.Application.Configuration.BdoHostConfiguration
  id: BdoHostConfiguration
  parent: BindOpen.Application.Configuration
  children:
  - BindOpen.Application.Configuration.BdoHostConfiguration.#ctor
  - BindOpen.Application.Configuration.BdoHostConfiguration.#ctor(BindOpen.Data.Elements.IDataElement[])
  langs:
  - csharp
  - vb
  name: BdoHostConfiguration
  nameWithType: BdoHostConfiguration
  fullName: BindOpen.Application.Configuration.BdoHostConfiguration
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Configuration
  summary: "\nThis class represents a BindOpen host application configuration.\n"
  syntax:
    content: 'public class BdoHostConfiguration : BdoBaseConfiguration, IBdoHostConfiguration, IBdoBaseConfiguration, IDataElementSet, IDataItemSet<DataElement>, IIdentifiedDataItem, IDataItem, ICloneable, IDisposable, IIdentified, IReferenced, INamed, ISavable, IGloballyDescribed'
    content.vb: >-
      Public Class BdoHostConfiguration
          Inherits BdoBaseConfiguration
          Implements IBdoHostConfiguration, IBdoBaseConfiguration, IDataElementSet, IDataItemSet(Of DataElement), IIdentifiedDataItem, IDataItem, ICloneable, IDisposable, IIdentified, IReferenced, INamed, ISavable, IGloballyDescribed
  inheritance:
  - System.Object
  implements:
  - BindOpen.Application.Configuration.IBdoHostConfiguration
  - BindOpen.Application.Configuration.IBdoBaseConfiguration
  - BindOpen.Data.Elements.IDataElementSet
  - BindOpen.Data.Items.IDataItemSet{BindOpen.Data.Elements.DataElement}
  - BindOpen.Data.Items.IIdentifiedDataItem
  - BindOpen.Data.Items.IDataItem
  - System.ICloneable
  - System.IDisposable
  - BindOpen.Data.Items.IIdentified
  - BindOpen.Data.Items.IReferenced
  - BindOpen.Data.Items.INamed
  - BindOpen.Data.Items.ISavable
  - BindOpen.Data.Items.IGloballyDescribed
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: BindOpen.Application.Configuration.BdoHostConfiguration.#ctor
  commentId: M:BindOpen.Application.Configuration.BdoHostConfiguration.#ctor
  id: '#ctor'
  parent: BindOpen.Application.Configuration.BdoHostConfiguration
  langs:
  - csharp
  - vb
  name: BdoHostConfiguration()
  nameWithType: BdoHostConfiguration.BdoHostConfiguration()
  fullName: BindOpen.Application.Configuration.BdoHostConfiguration.BdoHostConfiguration()
  type: Constructor
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Configuration
  summary: "\nInstantiates a new instance of the BdoHostConfiguration class.\n"
  syntax:
    content: public BdoHostConfiguration()
    content.vb: Public Sub New
  overload: BindOpen.Application.Configuration.BdoHostConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Configuration.BdoHostConfiguration.#ctor(BindOpen.Data.Elements.IDataElement[])
  commentId: M:BindOpen.Application.Configuration.BdoHostConfiguration.#ctor(BindOpen.Data.Elements.IDataElement[])
  id: '#ctor(BindOpen.Data.Elements.IDataElement[])'
  parent: BindOpen.Application.Configuration.BdoHostConfiguration
  langs:
  - csharp
  - vb
  name: BdoHostConfiguration(IDataElement[])
  nameWithType: BdoHostConfiguration.BdoHostConfiguration(IDataElement[])
  fullName: BindOpen.Application.Configuration.BdoHostConfiguration.BdoHostConfiguration(BindOpen.Data.Elements.IDataElement[])
  type: Constructor
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Configuration
  summary: "\nInstantiates a new instance of the BdoHostConfiguration class.\n"
  syntax:
    content: public BdoHostConfiguration(params IDataElement[] items)
    parameters:
    - id: items
      type: BindOpen.Data.Elements.IDataElement[]
      description: The items to consider.
    content.vb: Public Sub New(ParamArray items As IDataElement())
  overload: BindOpen.Application.Configuration.BdoHostConfiguration.#ctor*
  nameWithType.vb: BdoHostConfiguration.BdoHostConfiguration(IDataElement())
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: BindOpen.Application.Configuration.BdoHostConfiguration.BdoHostConfiguration(BindOpen.Data.Elements.IDataElement())
  name.vb: BdoHostConfiguration(IDataElement())
references:
- uid: BindOpen.Application.Configuration
  commentId: N:BindOpen.Application.Configuration
  isExternal: true
  name: BindOpen.Application.Configuration
  nameWithType: BindOpen.Application.Configuration
  fullName: BindOpen.Application.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: BindOpen.Application.Configuration.IBdoHostConfiguration
  commentId: T:BindOpen.Application.Configuration.IBdoHostConfiguration
  parent: BindOpen.Application.Configuration
  isExternal: true
  name: IBdoHostConfiguration
  nameWithType: IBdoHostConfiguration
  fullName: BindOpen.Application.Configuration.IBdoHostConfiguration
- uid: BindOpen.Application.Configuration.IBdoBaseConfiguration
  isExternal: true
  name: IBdoBaseConfiguration
  nameWithType: IBdoBaseConfiguration
  fullName: BindOpen.Application.Configuration.IBdoBaseConfiguration
- uid: BindOpen.Data.Elements.IDataElementSet
  isExternal: true
  name: IDataElementSet
  nameWithType: IDataElementSet
  fullName: BindOpen.Data.Elements.IDataElementSet
- uid: BindOpen.Data.Items.IDataItemSet{BindOpen.Data.Elements.DataElement}
  commentId: '!:BindOpen.Data.Items.IDataItemSet{BindOpen.Data.Elements.DataElement}'
  definition: BindOpen.Data.Items.IDataItemSet`1
  name: IDataItemSet<DataElement>
  nameWithType: IDataItemSet<DataElement>
  fullName: BindOpen.Data.Items.IDataItemSet<BindOpen.Data.Elements.DataElement>
  nameWithType.vb: IDataItemSet(Of DataElement)
  fullName.vb: BindOpen.Data.Items.IDataItemSet(Of BindOpen.Data.Elements.DataElement)
  name.vb: IDataItemSet(Of DataElement)
  spec.csharp:
  - uid: BindOpen.Data.Items.IDataItemSet`1
    name: IDataItemSet
    nameWithType: IDataItemSet
    fullName: BindOpen.Data.Items.IDataItemSet
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: BindOpen.Data.Elements.DataElement
    name: DataElement
    nameWithType: DataElement
    fullName: BindOpen.Data.Elements.DataElement
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: BindOpen.Data.Items.IDataItemSet`1
    name: IDataItemSet
    nameWithType: IDataItemSet
    fullName: BindOpen.Data.Items.IDataItemSet
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: BindOpen.Data.Elements.DataElement
    name: DataElement
    nameWithType: DataElement
    fullName: BindOpen.Data.Elements.DataElement
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Data.Items.IIdentifiedDataItem
  isExternal: true
  name: IIdentifiedDataItem
  nameWithType: IIdentifiedDataItem
  fullName: BindOpen.Data.Items.IIdentifiedDataItem
- uid: BindOpen.Data.Items.IDataItem
  isExternal: true
  name: IDataItem
  nameWithType: IDataItem
  fullName: BindOpen.Data.Items.IDataItem
- uid: System.ICloneable
  isExternal: true
  name: ICloneable
  nameWithType: ICloneable
  fullName: System.ICloneable
- uid: System.IDisposable
  isExternal: true
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: BindOpen.Data.Items.IIdentified
  isExternal: true
  name: IIdentified
  nameWithType: IIdentified
  fullName: BindOpen.Data.Items.IIdentified
- uid: BindOpen.Data.Items.IReferenced
  isExternal: true
  name: IReferenced
  nameWithType: IReferenced
  fullName: BindOpen.Data.Items.IReferenced
- uid: BindOpen.Data.Items.INamed
  isExternal: true
  name: INamed
  nameWithType: INamed
  fullName: BindOpen.Data.Items.INamed
- uid: BindOpen.Data.Items.ISavable
  isExternal: true
  name: ISavable
  nameWithType: ISavable
  fullName: BindOpen.Data.Items.ISavable
- uid: BindOpen.Data.Items.IGloballyDescribed
  isExternal: true
  name: IGloballyDescribed
  nameWithType: IGloballyDescribed
  fullName: BindOpen.Data.Items.IGloballyDescribed
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: BindOpen.Data.Items.IDataItemSet`1
  isExternal: true
  name: IDataItemSet<>
  nameWithType: IDataItemSet<>
  fullName: BindOpen.Data.Items.IDataItemSet<>
  nameWithType.vb: IDataItemSet(Of )
  fullName.vb: BindOpen.Data.Items.IDataItemSet(Of )
  name.vb: IDataItemSet(Of )
  spec.csharp:
  - uid: BindOpen.Data.Items.IDataItemSet`1
    name: IDataItemSet
    nameWithType: IDataItemSet
    fullName: BindOpen.Data.Items.IDataItemSet
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: BindOpen.Data.Items.IDataItemSet`1
    name: IDataItemSet
    nameWithType: IDataItemSet
    fullName: BindOpen.Data.Items.IDataItemSet
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Application.Configuration.BdoHostConfiguration.#ctor*
  commentId: Overload:BindOpen.Application.Configuration.BdoHostConfiguration.#ctor
  isExternal: true
  name: BdoHostConfiguration
  nameWithType: BdoHostConfiguration.BdoHostConfiguration
  fullName: BindOpen.Application.Configuration.BdoHostConfiguration.BdoHostConfiguration
- uid: BindOpen.Data.Elements.IDataElement[]
  isExternal: true
  name: IDataElement[]
  nameWithType: IDataElement[]
  fullName: BindOpen.Data.Elements.IDataElement[]
  nameWithType.vb: IDataElement()
  fullName.vb: BindOpen.Data.Elements.IDataElement()
  name.vb: IDataElement()
  spec.csharp:
  - uid: BindOpen.Data.Elements.IDataElement
    name: IDataElement
    nameWithType: IDataElement
    fullName: BindOpen.Data.Elements.IDataElement
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: BindOpen.Data.Elements.IDataElement
    name: IDataElement
    nameWithType: IDataElement
    fullName: BindOpen.Data.Elements.IDataElement
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
shouldSkipMarkup: true
