### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  commentId: T:BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  id: ApplicationPrivilege.ApplicationPrivilegeEntityKind
  parent: BindOpen.Application.Rights
  children:
  - BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Any
  - BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Class
  - BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Section
  - BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.value__
  langs:
  - csharp
  - vb
  name: ApplicationPrivilege.ApplicationPrivilegeEntityKind
  nameWithType: ApplicationPrivilege.ApplicationPrivilegeEntityKind
  fullName: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Rights
  summary: "\nThis enumeration lists the possible entity kinds of application privilege.\n"
  syntax:
    content: 'public sealed class ApplicationPrivilegeEntityKind : Enum'
    content.vb: >-
      Public NotInheritable Class ApplicationPrivilegeEntityKind
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.value__
  commentId: F:BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.value__
  id: value__
  parent: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: ApplicationPrivilege.ApplicationPrivilegeEntityKind.value__
  fullName: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.value__
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Rights
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Any
  commentId: F:BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Any
  id: Any
  parent: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  langs:
  - csharp
  - vb
  name: Any
  nameWithType: ApplicationPrivilege.ApplicationPrivilegeEntityKind.Any
  fullName: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Any
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Rights
  summary: "\nAny.\n"
  syntax:
    content: public const ApplicationPrivilege.ApplicationPrivilegeEntityKind Any
    return:
      type: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
    content.vb: Public Const Any As ApplicationPrivilege.ApplicationPrivilegeEntityKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Section
  commentId: F:BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Section
  id: Section
  parent: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  langs:
  - csharp
  - vb
  name: Section
  nameWithType: ApplicationPrivilege.ApplicationPrivilegeEntityKind.Section
  fullName: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Section
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Rights
  summary: "\nPage or page section.\n"
  syntax:
    content: public const ApplicationPrivilege.ApplicationPrivilegeEntityKind Section
    return:
      type: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
    content.vb: Public Const Section As ApplicationPrivilege.ApplicationPrivilegeEntityKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Class
  commentId: F:BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Class
  id: Class
  parent: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  langs:
  - csharp
  - vb
  name: Class
  nameWithType: ApplicationPrivilege.ApplicationPrivilegeEntityKind.Class
  fullName: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind.Class
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Rights
  summary: "\nObject class.\n"
  syntax:
    content: public const ApplicationPrivilege.ApplicationPrivilegeEntityKind Class
    return:
      type: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
    content.vb: Public Const Class As ApplicationPrivilege.ApplicationPrivilegeEntityKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BindOpen.Application.Rights
  commentId: N:BindOpen.Application.Rights
  isExternal: true
  name: BindOpen.Application.Rights
  nameWithType: BindOpen.Application.Rights
  fullName: BindOpen.Application.Rights
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  commentId: T:BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  parent: BindOpen.Application.Rights
  isExternal: true
  name: ApplicationPrivilege.ApplicationPrivilegeEntityKind
  nameWithType: ApplicationPrivilege.ApplicationPrivilegeEntityKind
  fullName: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
shouldSkipMarkup: true
