### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Navigation.ActionKinds
  commentId: T:BindOpen.Application.Navigation.ActionKinds
  id: ActionKinds
  parent: BindOpen.Application.Navigation
  children:
  - BindOpen.Application.Navigation.ActionKinds.Access
  - BindOpen.Application.Navigation.ActionKinds.Create
  - BindOpen.Application.Navigation.ActionKinds.Custom
  - BindOpen.Application.Navigation.ActionKinds.Delete
  - BindOpen.Application.Navigation.ActionKinds.Download
  - BindOpen.Application.Navigation.ActionKinds.Edit
  - BindOpen.Application.Navigation.ActionKinds.Export
  - BindOpen.Application.Navigation.ActionKinds.FullEdit
  - BindOpen.Application.Navigation.ActionKinds.Import
  - BindOpen.Application.Navigation.ActionKinds.MergeDbQuery
  - BindOpen.Application.Navigation.ActionKinds.None
  - BindOpen.Application.Navigation.ActionKinds.Print
  - BindOpen.Application.Navigation.ActionKinds.Search
  - BindOpen.Application.Navigation.ActionKinds.value__
  - BindOpen.Application.Navigation.ActionKinds.View
  langs:
  - csharp
  - vb
  name: ActionKinds
  nameWithType: ActionKinds
  fullName: BindOpen.Application.Navigation.ActionKinds
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nThis enumerates the possible kinds of action.\n"
  syntax:
    content: 'public sealed class ActionKinds : Enum'
    content.vb: >-
      Public NotInheritable Class ActionKinds
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: BindOpen.Application.Navigation.ActionKinds.value__
  commentId: F:BindOpen.Application.Navigation.ActionKinds.value__
  id: value__
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: ActionKinds.value__
  fullName: BindOpen.Application.Navigation.ActionKinds.value__
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Navigation.ActionKinds.None
  commentId: F:BindOpen.Application.Navigation.ActionKinds.None
  id: None
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ActionKinds.None
  fullName: BindOpen.Application.Navigation.ActionKinds.None
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nNone can access.\n"
  syntax:
    content: public const ActionKinds None
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const None As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Access
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Access
  id: Access
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Access
  nameWithType: ActionKinds.Access
  fullName: BindOpen.Application.Navigation.ActionKinds.Access
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nAccess.\n"
  syntax:
    content: public const ActionKinds Access
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Access As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.View
  commentId: F:BindOpen.Application.Navigation.ActionKinds.View
  id: View
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: View
  nameWithType: ActionKinds.View
  fullName: BindOpen.Application.Navigation.ActionKinds.View
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nView.\n"
  syntax:
    content: public const ActionKinds View
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const View As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Download
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Download
  id: Download
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Download
  nameWithType: ActionKinds.Download
  fullName: BindOpen.Application.Navigation.ActionKinds.Download
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nDownload.\n"
  syntax:
    content: public const ActionKinds Download
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Download As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Print
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Print
  id: Print
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Print
  nameWithType: ActionKinds.Print
  fullName: BindOpen.Application.Navigation.ActionKinds.Print
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nPrint.\n"
  syntax:
    content: public const ActionKinds Print
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Print As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Search
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Search
  id: Search
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Search
  nameWithType: ActionKinds.Search
  fullName: BindOpen.Application.Navigation.ActionKinds.Search
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nSearch.\n"
  syntax:
    content: public const ActionKinds Search
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Search As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Create
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Create
  id: Create
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Create
  nameWithType: ActionKinds.Create
  fullName: BindOpen.Application.Navigation.ActionKinds.Create
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nCreate.\n"
  syntax:
    content: public const ActionKinds Create
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Create As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Edit
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Edit
  id: Edit
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Edit
  nameWithType: ActionKinds.Edit
  fullName: BindOpen.Application.Navigation.ActionKinds.Edit
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nEdit.\n"
  syntax:
    content: public const ActionKinds Edit
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Edit As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.FullEdit
  commentId: F:BindOpen.Application.Navigation.ActionKinds.FullEdit
  id: FullEdit
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: FullEdit
  nameWithType: ActionKinds.FullEdit
  fullName: BindOpen.Application.Navigation.ActionKinds.FullEdit
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nFull edit.\n"
  syntax:
    content: public const ActionKinds FullEdit
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const FullEdit As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Delete
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Delete
  id: Delete
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Delete
  nameWithType: ActionKinds.Delete
  fullName: BindOpen.Application.Navigation.ActionKinds.Delete
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nDelete.\n"
  syntax:
    content: public const ActionKinds Delete
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Delete As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.MergeDbQuery
  commentId: F:BindOpen.Application.Navigation.ActionKinds.MergeDbQuery
  id: MergeDbQuery
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: MergeDbQuery
  nameWithType: ActionKinds.MergeDbQuery
  fullName: BindOpen.Application.Navigation.ActionKinds.MergeDbQuery
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nMergeDbQuery.\n"
  syntax:
    content: public const ActionKinds MergeDbQuery
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const MergeDbQuery As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Import
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Import
  id: Import
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Import
  nameWithType: ActionKinds.Import
  fullName: BindOpen.Application.Navigation.ActionKinds.Import
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nImport.\n"
  syntax:
    content: public const ActionKinds Import
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Import As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Export
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Export
  id: Export
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Export
  nameWithType: ActionKinds.Export
  fullName: BindOpen.Application.Navigation.ActionKinds.Export
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nExport.\n"
  syntax:
    content: public const ActionKinds Export
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Export As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Navigation.ActionKinds.Custom
  commentId: F:BindOpen.Application.Navigation.ActionKinds.Custom
  id: Custom
  parent: BindOpen.Application.Navigation.ActionKinds
  langs:
  - csharp
  - vb
  name: Custom
  nameWithType: ActionKinds.Custom
  fullName: BindOpen.Application.Navigation.ActionKinds.Custom
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Navigation
  summary: "\nCustom.\n"
  syntax:
    content: public const ActionKinds Custom
    return:
      type: BindOpen.Application.Navigation.ActionKinds
    content.vb: Public Const Custom As ActionKinds
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BindOpen.Application.Navigation
  commentId: N:BindOpen.Application.Navigation
  isExternal: true
  name: BindOpen.Application.Navigation
  nameWithType: BindOpen.Application.Navigation
  fullName: BindOpen.Application.Navigation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: BindOpen.Application.Navigation.ActionKinds
  commentId: T:BindOpen.Application.Navigation.ActionKinds
  parent: BindOpen.Application.Navigation
  isExternal: true
  name: ActionKinds
  nameWithType: ActionKinds
  fullName: BindOpen.Application.Navigation.ActionKinds
shouldSkipMarkup: true
