### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Modules
  commentId: N:BindOpen.Application.Modules
  id: BindOpen.Application.Modules
  children:
  - BindOpen.Application.Modules.ApplicationModuleInstance
  - BindOpen.Application.Modules.ApplicationModuleKind
  - BindOpen.Application.Modules.ApplicationModuleSubKind
  - BindOpen.Application.Modules.AppModule
  - BindOpen.Application.Modules.AppSection
  - BindOpen.Application.Modules.IApplicationModuleInstance
  - BindOpen.Application.Modules.IAppModule
  - BindOpen.Application.Modules.IAppSection
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Modules
  nameWithType: BindOpen.Application.Modules
  fullName: BindOpen.Application.Modules
  type: Namespace
  assemblies:
  - BindOpen.Runtime
references:
- uid: BindOpen.Application.Modules.ApplicationModuleInstance
  commentId: T:BindOpen.Application.Modules.ApplicationModuleInstance
  isExternal: true
  name: ApplicationModuleInstance
  nameWithType: ApplicationModuleInstance
  fullName: BindOpen.Application.Modules.ApplicationModuleInstance
- uid: BindOpen.Application.Modules.ApplicationModuleKind
  commentId: T:BindOpen.Application.Modules.ApplicationModuleKind
  parent: BindOpen.Application.Modules
  isExternal: true
  name: ApplicationModuleKind
  nameWithType: ApplicationModuleKind
  fullName: BindOpen.Application.Modules.ApplicationModuleKind
- uid: BindOpen.Application.Modules.ApplicationModuleSubKind
  commentId: T:BindOpen.Application.Modules.ApplicationModuleSubKind
  parent: BindOpen.Application.Modules
  isExternal: true
  name: ApplicationModuleSubKind
  nameWithType: ApplicationModuleSubKind
  fullName: BindOpen.Application.Modules.ApplicationModuleSubKind
- uid: BindOpen.Application.Modules.AppModule
  commentId: T:BindOpen.Application.Modules.AppModule
  isExternal: true
  name: AppModule
  nameWithType: AppModule
  fullName: BindOpen.Application.Modules.AppModule
- uid: BindOpen.Application.Modules.AppSection
  commentId: T:BindOpen.Application.Modules.AppSection
  isExternal: true
  name: AppSection
  nameWithType: AppSection
  fullName: BindOpen.Application.Modules.AppSection
- uid: BindOpen.Application.Modules.IApplicationModuleInstance
  commentId: T:BindOpen.Application.Modules.IApplicationModuleInstance
  parent: BindOpen.Application.Modules
  isExternal: true
  name: IApplicationModuleInstance
  nameWithType: IApplicationModuleInstance
  fullName: BindOpen.Application.Modules.IApplicationModuleInstance
- uid: BindOpen.Application.Modules.IAppModule
  commentId: T:BindOpen.Application.Modules.IAppModule
  parent: BindOpen.Application.Modules
  isExternal: true
  name: IAppModule
  nameWithType: IAppModule
  fullName: BindOpen.Application.Modules.IAppModule
- uid: BindOpen.Application.Modules.IAppSection
  commentId: T:BindOpen.Application.Modules.IAppSection
  parent: BindOpen.Application.Modules
  isExternal: true
  name: IAppSection
  nameWithType: IAppSection
  fullName: BindOpen.Application.Modules.IAppSection
- uid: BindOpen.Application.Modules
  commentId: N:BindOpen.Application.Modules
  isExternal: true
  name: BindOpen.Application.Modules
  nameWithType: BindOpen.Application.Modules
  fullName: BindOpen.Application.Modules
shouldSkipMarkup: true
