### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Services.IBdoTrigeredService
  commentId: T:BindOpen.Application.Services.IBdoTrigeredService
  id: IBdoTrigeredService
  parent: BindOpen.Application.Services
  children:
  - BindOpen.Application.Services.IBdoTrigeredService.ExecutionFails
  - BindOpen.Application.Services.IBdoTrigeredService.ExecutionSucceedes
  - BindOpen.Application.Services.IBdoTrigeredService.StartFails
  - BindOpen.Application.Services.IBdoTrigeredService.StartSucceeds
  langs:
  - csharp
  - vb
  name: IBdoTrigeredService
  nameWithType: IBdoTrigeredService
  fullName: BindOpen.Application.Services.IBdoTrigeredService
  type: Interface
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nThe interface defines the BindOpen service.\n"
  syntax:
    content: public interface IBdoTrigeredService
    content.vb: Public Interface IBdoTrigeredService
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: BindOpen.Application.Services.IBdoTrigeredService.StartSucceeds
  commentId: M:BindOpen.Application.Services.IBdoTrigeredService.StartSucceeds
  id: StartSucceeds
  parent: BindOpen.Application.Services.IBdoTrigeredService
  langs:
  - csharp
  - vb
  name: StartSucceeds()
  nameWithType: IBdoTrigeredService.StartSucceeds()
  fullName: BindOpen.Application.Services.IBdoTrigeredService.StartSucceeds()
  type: Method
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nIndicates that the start of this instance completes.\n"
  syntax:
    content: void StartSucceeds()
    content.vb: Sub StartSucceeds
  overload: BindOpen.Application.Services.IBdoTrigeredService.StartSucceeds*
- uid: BindOpen.Application.Services.IBdoTrigeredService.StartFails
  commentId: M:BindOpen.Application.Services.IBdoTrigeredService.StartFails
  id: StartFails
  parent: BindOpen.Application.Services.IBdoTrigeredService
  langs:
  - csharp
  - vb
  name: StartFails()
  nameWithType: IBdoTrigeredService.StartFails()
  fullName: BindOpen.Application.Services.IBdoTrigeredService.StartFails()
  type: Method
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nIndicates that the start of this instance fails.\n"
  syntax:
    content: void StartFails()
    content.vb: Sub StartFails
  overload: BindOpen.Application.Services.IBdoTrigeredService.StartFails*
- uid: BindOpen.Application.Services.IBdoTrigeredService.ExecutionSucceedes
  commentId: M:BindOpen.Application.Services.IBdoTrigeredService.ExecutionSucceedes
  id: ExecutionSucceedes
  parent: BindOpen.Application.Services.IBdoTrigeredService
  langs:
  - csharp
  - vb
  name: ExecutionSucceedes()
  nameWithType: IBdoTrigeredService.ExecutionSucceedes()
  fullName: BindOpen.Application.Services.IBdoTrigeredService.ExecutionSucceedes()
  type: Method
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nIndicates that this instance execution succeeds.\n"
  syntax:
    content: void ExecutionSucceedes()
    content.vb: Sub ExecutionSucceedes
  overload: BindOpen.Application.Services.IBdoTrigeredService.ExecutionSucceedes*
- uid: BindOpen.Application.Services.IBdoTrigeredService.ExecutionFails
  commentId: M:BindOpen.Application.Services.IBdoTrigeredService.ExecutionFails
  id: ExecutionFails
  parent: BindOpen.Application.Services.IBdoTrigeredService
  langs:
  - csharp
  - vb
  name: ExecutionFails()
  nameWithType: IBdoTrigeredService.ExecutionFails()
  fullName: BindOpen.Application.Services.IBdoTrigeredService.ExecutionFails()
  type: Method
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nIndicates that this instance execution fails.\n"
  syntax:
    content: void ExecutionFails()
    content.vb: Sub ExecutionFails
  overload: BindOpen.Application.Services.IBdoTrigeredService.ExecutionFails*
references:
- uid: BindOpen.Application.Services
  commentId: N:BindOpen.Application.Services
  isExternal: true
  name: BindOpen.Application.Services
  nameWithType: BindOpen.Application.Services
  fullName: BindOpen.Application.Services
- uid: BindOpen.Application.Services.IBdoTrigeredService.StartSucceeds*
  commentId: Overload:BindOpen.Application.Services.IBdoTrigeredService.StartSucceeds
  isExternal: true
  name: StartSucceeds
  nameWithType: IBdoTrigeredService.StartSucceeds
  fullName: BindOpen.Application.Services.IBdoTrigeredService.StartSucceeds
- uid: BindOpen.Application.Services.IBdoTrigeredService.StartFails*
  commentId: Overload:BindOpen.Application.Services.IBdoTrigeredService.StartFails
  isExternal: true
  name: StartFails
  nameWithType: IBdoTrigeredService.StartFails
  fullName: BindOpen.Application.Services.IBdoTrigeredService.StartFails
- uid: BindOpen.Application.Services.IBdoTrigeredService.ExecutionSucceedes*
  commentId: Overload:BindOpen.Application.Services.IBdoTrigeredService.ExecutionSucceedes
  isExternal: true
  name: ExecutionSucceedes
  nameWithType: IBdoTrigeredService.ExecutionSucceedes
  fullName: BindOpen.Application.Services.IBdoTrigeredService.ExecutionSucceedes
- uid: BindOpen.Application.Services.IBdoTrigeredService.ExecutionFails*
  commentId: Overload:BindOpen.Application.Services.IBdoTrigeredService.ExecutionFails
  isExternal: true
  name: ExecutionFails
  nameWithType: IBdoTrigeredService.ExecutionFails
  fullName: BindOpen.Application.Services.IBdoTrigeredService.ExecutionFails
shouldSkipMarkup: true
