### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Modules.ApplicationModuleKind
  commentId: T:BindOpen.Application.Modules.ApplicationModuleKind
  id: ApplicationModuleKind
  parent: BindOpen.Application.Modules
  children:
  - BindOpen.Application.Modules.ApplicationModuleKind.None
  - BindOpen.Application.Modules.ApplicationModuleKind.value__
  - BindOpen.Application.Modules.ApplicationModuleKind.WebService
  - BindOpen.Application.Modules.ApplicationModuleKind.Website
  - BindOpen.Application.Modules.ApplicationModuleKind.WindowsDesktop
  - BindOpen.Application.Modules.ApplicationModuleKind.WindowsService
  langs:
  - csharp
  - vb
  name: ApplicationModuleKind
  nameWithType: ApplicationModuleKind
  fullName: BindOpen.Application.Modules.ApplicationModuleKind
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Modules
  summary: "\nThis enumerates the possible kinds of visitor application module.\n"
  syntax:
    content: 'public sealed class ApplicationModuleKind : Enum'
    content.vb: >-
      Public NotInheritable Class ApplicationModuleKind
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: BindOpen.Application.Modules.ApplicationModuleKind.value__
  commentId: F:BindOpen.Application.Modules.ApplicationModuleKind.value__
  id: value__
  parent: BindOpen.Application.Modules.ApplicationModuleKind
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: ApplicationModuleKind.value__
  fullName: BindOpen.Application.Modules.ApplicationModuleKind.value__
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Modules
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: BindOpen.Application.Modules.ApplicationModuleKind.None
  commentId: F:BindOpen.Application.Modules.ApplicationModuleKind.None
  id: None
  parent: BindOpen.Application.Modules.ApplicationModuleKind
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ApplicationModuleKind.None
  fullName: BindOpen.Application.Modules.ApplicationModuleKind.None
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Modules
  summary: "\nNone. Used when the application module is not defined.\n"
  syntax:
    content: public const ApplicationModuleKind None
    return:
      type: BindOpen.Application.Modules.ApplicationModuleKind
    content.vb: Public Const None As ApplicationModuleKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Modules.ApplicationModuleKind.Website
  commentId: F:BindOpen.Application.Modules.ApplicationModuleKind.Website
  id: Website
  parent: BindOpen.Application.Modules.ApplicationModuleKind
  langs:
  - csharp
  - vb
  name: Website
  nameWithType: ApplicationModuleKind.Website
  fullName: BindOpen.Application.Modules.ApplicationModuleKind.Website
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Modules
  summary: "\nWebsite.\n"
  syntax:
    content: public const ApplicationModuleKind Website
    return:
      type: BindOpen.Application.Modules.ApplicationModuleKind
    content.vb: Public Const Website As ApplicationModuleKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Modules.ApplicationModuleKind.WebService
  commentId: F:BindOpen.Application.Modules.ApplicationModuleKind.WebService
  id: WebService
  parent: BindOpen.Application.Modules.ApplicationModuleKind
  langs:
  - csharp
  - vb
  name: WebService
  nameWithType: ApplicationModuleKind.WebService
  fullName: BindOpen.Application.Modules.ApplicationModuleKind.WebService
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Modules
  summary: "\nWeb service.\n"
  syntax:
    content: public const ApplicationModuleKind WebService
    return:
      type: BindOpen.Application.Modules.ApplicationModuleKind
    content.vb: Public Const WebService As ApplicationModuleKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Modules.ApplicationModuleKind.WindowsDesktop
  commentId: F:BindOpen.Application.Modules.ApplicationModuleKind.WindowsDesktop
  id: WindowsDesktop
  parent: BindOpen.Application.Modules.ApplicationModuleKind
  langs:
  - csharp
  - vb
  name: WindowsDesktop
  nameWithType: ApplicationModuleKind.WindowsDesktop
  fullName: BindOpen.Application.Modules.ApplicationModuleKind.WindowsDesktop
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Modules
  summary: "\nWindows desktop.\n"
  syntax:
    content: public const ApplicationModuleKind WindowsDesktop
    return:
      type: BindOpen.Application.Modules.ApplicationModuleKind
    content.vb: Public Const WindowsDesktop As ApplicationModuleKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BindOpen.Application.Modules.ApplicationModuleKind.WindowsService
  commentId: F:BindOpen.Application.Modules.ApplicationModuleKind.WindowsService
  id: WindowsService
  parent: BindOpen.Application.Modules.ApplicationModuleKind
  langs:
  - csharp
  - vb
  name: WindowsService
  nameWithType: ApplicationModuleKind.WindowsService
  fullName: BindOpen.Application.Modules.ApplicationModuleKind.WindowsService
  type: Field
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Modules
  summary: "\nWindows service.\n"
  syntax:
    content: public const ApplicationModuleKind WindowsService
    return:
      type: BindOpen.Application.Modules.ApplicationModuleKind
    content.vb: Public Const WindowsService As ApplicationModuleKind
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BindOpen.Application.Modules
  commentId: N:BindOpen.Application.Modules
  isExternal: true
  name: BindOpen.Application.Modules
  nameWithType: BindOpen.Application.Modules
  fullName: BindOpen.Application.Modules
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: BindOpen.Application.Modules.ApplicationModuleKind
  commentId: T:BindOpen.Application.Modules.ApplicationModuleKind
  parent: BindOpen.Application.Modules
  isExternal: true
  name: ApplicationModuleKind
  nameWithType: ApplicationModuleKind
  fullName: BindOpen.Application.Modules.ApplicationModuleKind
shouldSkipMarkup: true
