### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Configuration.IBdoHostConfiguration
  commentId: T:BindOpen.Application.Configuration.IBdoHostConfiguration
  id: IBdoHostConfiguration
  parent: BindOpen.Application.Configuration
  children: []
  langs:
  - csharp
  - vb
  name: IBdoHostConfiguration
  nameWithType: IBdoHostConfiguration
  fullName: BindOpen.Application.Configuration.IBdoHostConfiguration
  type: Interface
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Configuration
  summary: "\nThis interface defines host application configuration.\n"
  syntax:
    content: 'public interface IBdoHostConfiguration : IBdoBaseConfiguration, IDataElementSet, IDataItemSet<DataElement>, IIdentifiedDataItem, IDataItem, ICloneable, IDisposable, IIdentified, IReferenced, INamed, ISavable, IGloballyDescribed'
    content.vb: >-
      Public Interface IBdoHostConfiguration
          Inherits IBdoBaseConfiguration, IDataElementSet, IDataItemSet(Of DataElement), IIdentifiedDataItem, IDataItem, ICloneable, IDisposable, IIdentified, IReferenced, INamed, ISavable, IGloballyDescribed
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: BindOpen.Application.Configuration
  commentId: N:BindOpen.Application.Configuration
  isExternal: true
  name: BindOpen.Application.Configuration
  nameWithType: BindOpen.Application.Configuration
  fullName: BindOpen.Application.Configuration
shouldSkipMarkup: true
