### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Services.TBdoServiceOptions`2
  commentId: T:BindOpen.Application.Services.TBdoServiceOptions`2
  id: TBdoServiceOptions`2
  parent: BindOpen.Application.Services
  children:
  - BindOpen.Application.Services.TBdoServiceOptions`2.#ctor(BindOpen.System.Diagnostics.Loggers.IBdoLogger[],System.Func{`1,`0})
  - BindOpen.Application.Services.TBdoServiceOptions`2.FuncSettingsConverter
  - BindOpen.Application.Services.TBdoServiceOptions`2.Loggers
  langs:
  - csharp
  - vb
  name: TBdoServiceOptions<SServ, SHost>
  nameWithType: TBdoServiceOptions<SServ, SHost>
  fullName: BindOpen.Application.Services.TBdoServiceOptions<SServ, SHost>
  type: Class
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nThis class represents a service options provider.\n"
  remarks: The genericity was added to insure depency injection.
  syntax:
    content: >-
      public class TBdoServiceOptions<SServ, SHost> : Object, ITBdoServiceOptions<SServ, SHost> where SServ : class, IBdoSettings, new()
          where SHost : IBdoAppSettings
    typeParameters:
    - id: SServ
    - id: SHost
    content.vb: >-
      Public Class TBdoServiceOptions(Of SServ As {Class, IBdoSettings, New}, SHost As IBdoAppSettings)
          Inherits Object
          Implements ITBdoServiceOptions(Of SServ, SHost)
  inheritance:
  - System.Object
  implements:
  - BindOpen.Application.Services.ITBdoServiceOptions{{SServ},{SHost}}
  nameWithType.vb: TBdoServiceOptions(Of SServ, SHost)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: BindOpen.Application.Services.TBdoServiceOptions(Of SServ, SHost)
  name.vb: TBdoServiceOptions(Of SServ, SHost)
- uid: BindOpen.Application.Services.TBdoServiceOptions`2.#ctor(BindOpen.System.Diagnostics.Loggers.IBdoLogger[],System.Func{`1,`0})
  commentId: M:BindOpen.Application.Services.TBdoServiceOptions`2.#ctor(BindOpen.System.Diagnostics.Loggers.IBdoLogger[],System.Func{`1,`0})
  id: '#ctor(BindOpen.System.Diagnostics.Loggers.IBdoLogger[],System.Func{`1,`0})'
  parent: BindOpen.Application.Services.TBdoServiceOptions`2
  langs:
  - csharp
  - vb
  name: TBdoServiceOptions(IBdoLogger[], Func<SHost, SServ>)
  nameWithType: TBdoServiceOptions<SServ, SHost>.TBdoServiceOptions(IBdoLogger[], Func<SHost, SServ>)
  fullName: BindOpen.Application.Services.TBdoServiceOptions<SServ, SHost>.TBdoServiceOptions(BindOpen.System.Diagnostics.Loggers.IBdoLogger[], System.Func<SHost, SServ>)
  type: Constructor
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nInstantiates a new instance of the TBdoHostServiceOptions class.\n"
  syntax:
    content: public TBdoServiceOptions(IBdoLogger[] loggers = null, Func<SHost, SServ> funcSettingsConverter = null)
    parameters:
    - id: loggers
      type: BindOpen.System.Diagnostics.Loggers.IBdoLogger[]
      description: The loggers to consider.
    - id: funcSettingsConverter
      type: System.Func{{SHost},{SServ}}
      description: The settings converter function to consider.
    content.vb: Public Sub New(loggers As IBdoLogger() = Nothing, funcSettingsConverter As Func(Of SHost, SServ) = Nothing)
  overload: BindOpen.Application.Services.TBdoServiceOptions`2.#ctor*
  nameWithType.vb: TBdoServiceOptions(Of SServ, SHost).TBdoServiceOptions(IBdoLogger(), Func(Of SHost, SServ))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: BindOpen.Application.Services.TBdoServiceOptions(Of SServ, SHost).TBdoServiceOptions(BindOpen.System.Diagnostics.Loggers.IBdoLogger(), System.Func(Of SHost, SServ))
  name.vb: TBdoServiceOptions(IBdoLogger(), Func(Of SHost, SServ))
- uid: BindOpen.Application.Services.TBdoServiceOptions`2.Loggers
  commentId: P:BindOpen.Application.Services.TBdoServiceOptions`2.Loggers
  id: Loggers
  parent: BindOpen.Application.Services.TBdoServiceOptions`2
  langs:
  - csharp
  - vb
  name: Loggers
  nameWithType: TBdoServiceOptions<SServ, SHost>.Loggers
  fullName: BindOpen.Application.Services.TBdoServiceOptions<SServ, SHost>.Loggers
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nThe loggers of this instance.\n"
  syntax:
    content: public List<IBdoLogger> Loggers { get; }
    parameters: []
    return:
      type: System.Collections.Generic.List{BindOpen.System.Diagnostics.Loggers.IBdoLogger}
    content.vb: Public ReadOnly Property Loggers As List(Of IBdoLogger)
  overload: BindOpen.Application.Services.TBdoServiceOptions`2.Loggers*
  implements:
  - BindOpen.Application.Services.ITBdoServiceOptions{{SServ},{SHost}}.Loggers
  nameWithType.vb: TBdoServiceOptions(Of SServ, SHost).Loggers
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
  fullName.vb: BindOpen.Application.Services.TBdoServiceOptions(Of SServ, SHost).Loggers
- uid: BindOpen.Application.Services.TBdoServiceOptions`2.FuncSettingsConverter
  commentId: P:BindOpen.Application.Services.TBdoServiceOptions`2.FuncSettingsConverter
  id: FuncSettingsConverter
  parent: BindOpen.Application.Services.TBdoServiceOptions`2
  langs:
  - csharp
  - vb
  name: FuncSettingsConverter
  nameWithType: TBdoServiceOptions<SServ, SHost>.FuncSettingsConverter
  fullName: BindOpen.Application.Services.TBdoServiceOptions<SServ, SHost>.FuncSettingsConverter
  type: Property
  source:
    path: BindOpen.Runtime
    isExternal: true
  assemblies:
  - BindOpen.Runtime
  namespace: BindOpen.Application.Services
  summary: "\nThe settings function of this instance.\n"
  syntax:
    content: public Func<SHost, SServ> FuncSettingsConverter { get; }
    parameters: []
    return:
      type: System.Func{{SHost},{SServ}}
    content.vb: Public ReadOnly Property FuncSettingsConverter As Func(Of SHost, SServ)
  overload: BindOpen.Application.Services.TBdoServiceOptions`2.FuncSettingsConverter*
  implements:
  - BindOpen.Application.Services.ITBdoServiceOptions{{SServ},{SHost}}.FuncSettingsConverter
  nameWithType.vb: TBdoServiceOptions(Of SServ, SHost).FuncSettingsConverter
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
  fullName.vb: BindOpen.Application.Services.TBdoServiceOptions(Of SServ, SHost).FuncSettingsConverter
references:
- uid: BindOpen.Application.Services
  commentId: N:BindOpen.Application.Services
  isExternal: true
  name: BindOpen.Application.Services
  nameWithType: BindOpen.Application.Services
  fullName: BindOpen.Application.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: BindOpen.Application.Services.ITBdoServiceOptions{{SServ},{SHost}}
  commentId: T:BindOpen.Application.Services.ITBdoServiceOptions{`0,`1}
  parent: BindOpen.Application.Services
  definition: BindOpen.Application.Services.ITBdoServiceOptions`2
  name: ITBdoServiceOptions<SServ, SHost>
  nameWithType: ITBdoServiceOptions<SServ, SHost>
  fullName: BindOpen.Application.Services.ITBdoServiceOptions<SServ, SHost>
  nameWithType.vb: ITBdoServiceOptions(Of SServ, SHost)
  fullName.vb: BindOpen.Application.Services.ITBdoServiceOptions(Of SServ, SHost)
  name.vb: ITBdoServiceOptions(Of SServ, SHost)
  spec.csharp:
  - uid: BindOpen.Application.Services.ITBdoServiceOptions`2
    name: ITBdoServiceOptions
    nameWithType: ITBdoServiceOptions
    fullName: BindOpen.Application.Services.ITBdoServiceOptions
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: SServ
    nameWithType: SServ
    fullName: SServ
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: SHost
    nameWithType: SHost
    fullName: SHost
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: BindOpen.Application.Services.ITBdoServiceOptions`2
    name: ITBdoServiceOptions
    nameWithType: ITBdoServiceOptions
    fullName: BindOpen.Application.Services.ITBdoServiceOptions
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: SServ
    nameWithType: SServ
    fullName: SServ
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: SHost
    nameWithType: SHost
    fullName: SHost
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: BindOpen.Application.Services.ITBdoServiceOptions`2
  commentId: T:BindOpen.Application.Services.ITBdoServiceOptions`2
  isExternal: true
  name: ITBdoServiceOptions<SServ, SHost>
  nameWithType: ITBdoServiceOptions<SServ, SHost>
  fullName: BindOpen.Application.Services.ITBdoServiceOptions<SServ, SHost>
  nameWithType.vb: ITBdoServiceOptions(Of SServ, SHost)
  fullName.vb: BindOpen.Application.Services.ITBdoServiceOptions(Of SServ, SHost)
  name.vb: ITBdoServiceOptions(Of SServ, SHost)
  spec.csharp:
  - uid: BindOpen.Application.Services.ITBdoServiceOptions`2
    name: ITBdoServiceOptions
    nameWithType: ITBdoServiceOptions
    fullName: BindOpen.Application.Services.ITBdoServiceOptions
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: SServ
    nameWithType: SServ
    fullName: SServ
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: SHost
    nameWithType: SHost
    fullName: SHost
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: BindOpen.Application.Services.ITBdoServiceOptions`2
    name: ITBdoServiceOptions
    nameWithType: ITBdoServiceOptions
    fullName: BindOpen.Application.Services.ITBdoServiceOptions
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: SServ
    nameWithType: SServ
    fullName: SServ
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: SHost
    nameWithType: SHost
    fullName: SHost
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Application.Services.TBdoServiceOptions`2.#ctor*
  commentId: Overload:BindOpen.Application.Services.TBdoServiceOptions`2.#ctor
  isExternal: true
  name: TBdoServiceOptions
  nameWithType: TBdoServiceOptions<SServ, SHost>.TBdoServiceOptions
  fullName: BindOpen.Application.Services.TBdoServiceOptions<SServ, SHost>.TBdoServiceOptions
  nameWithType.vb: TBdoServiceOptions(Of SServ, SHost).TBdoServiceOptions
  fullName.vb: BindOpen.Application.Services.TBdoServiceOptions(Of SServ, SHost).TBdoServiceOptions
- uid: BindOpen.System.Diagnostics.Loggers.IBdoLogger[]
  isExternal: true
  name: IBdoLogger[]
  nameWithType: IBdoLogger[]
  fullName: BindOpen.System.Diagnostics.Loggers.IBdoLogger[]
  nameWithType.vb: IBdoLogger()
  fullName.vb: BindOpen.System.Diagnostics.Loggers.IBdoLogger()
  name.vb: IBdoLogger()
  spec.csharp:
  - uid: BindOpen.System.Diagnostics.Loggers.IBdoLogger
    name: IBdoLogger
    nameWithType: IBdoLogger
    fullName: BindOpen.System.Diagnostics.Loggers.IBdoLogger
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: BindOpen.System.Diagnostics.Loggers.IBdoLogger
    name: IBdoLogger
    nameWithType: IBdoLogger
    fullName: BindOpen.System.Diagnostics.Loggers.IBdoLogger
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: System.Func{{SHost},{SServ}}
  commentId: '!:System.Func{`1,`0}'
  definition: System.Func`2
  name: Func<SHost, SServ>
  nameWithType: Func<SHost, SServ>
  fullName: System.Func<SHost, SServ>
  nameWithType.vb: Func(Of SHost, SServ)
  fullName.vb: System.Func(Of SHost, SServ)
  name.vb: Func(Of SHost, SServ)
  spec.csharp:
  - uid: System.Func`2
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: SHost
    nameWithType: SHost
    fullName: SHost
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: SServ
    nameWithType: SServ
    fullName: SServ
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: SHost
    nameWithType: SHost
    fullName: SHost
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: SServ
    nameWithType: SServ
    fullName: SServ
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Func`2
  isExternal: true
  name: Func<, >
  nameWithType: Func<, >
  fullName: System.Func<, >
  nameWithType.vb: Func(Of , )
  fullName.vb: System.Func(Of , )
  name.vb: Func(Of , )
  spec.csharp:
  - uid: System.Func`2
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Application.Services.TBdoServiceOptions`2.Loggers*
  commentId: Overload:BindOpen.Application.Services.TBdoServiceOptions`2.Loggers
  isExternal: true
  name: Loggers
  nameWithType: TBdoServiceOptions<SServ, SHost>.Loggers
  fullName: BindOpen.Application.Services.TBdoServiceOptions<SServ, SHost>.Loggers
  nameWithType.vb: TBdoServiceOptions(Of SServ, SHost).Loggers
  fullName.vb: BindOpen.Application.Services.TBdoServiceOptions(Of SServ, SHost).Loggers
- uid: BindOpen.Application.Services.ITBdoServiceOptions{{SServ},{SHost}}.Loggers
  commentId: P:BindOpen.Application.Services.ITBdoServiceOptions{`0,`1}.Loggers
  parent: BindOpen.Application.Services.ITBdoServiceOptions{{SServ},{SHost}}
  definition: BindOpen.Application.Services.ITBdoServiceOptions`2.Loggers
  name: Loggers
  nameWithType: ITBdoServiceOptions<SServ, SHost>.Loggers
  fullName: BindOpen.Application.Services.ITBdoServiceOptions<SServ, SHost>.Loggers
  nameWithType.vb: ITBdoServiceOptions(Of SServ, SHost).Loggers
  fullName.vb: BindOpen.Application.Services.ITBdoServiceOptions(Of SServ, SHost).Loggers
- uid: System.Collections.Generic.List{BindOpen.System.Diagnostics.Loggers.IBdoLogger}
  commentId: '!:System.Collections.Generic.List{BindOpen.System.Diagnostics.Loggers.IBdoLogger}'
  definition: System.Collections.Generic.List`1
  name: List<IBdoLogger>
  nameWithType: List<IBdoLogger>
  fullName: System.Collections.Generic.List<BindOpen.System.Diagnostics.Loggers.IBdoLogger>
  nameWithType.vb: List(Of IBdoLogger)
  fullName.vb: System.Collections.Generic.List(Of BindOpen.System.Diagnostics.Loggers.IBdoLogger)
  name.vb: List(Of IBdoLogger)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: BindOpen.System.Diagnostics.Loggers.IBdoLogger
    name: IBdoLogger
    nameWithType: IBdoLogger
    fullName: BindOpen.System.Diagnostics.Loggers.IBdoLogger
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: BindOpen.System.Diagnostics.Loggers.IBdoLogger
    name: IBdoLogger
    nameWithType: IBdoLogger
    fullName: BindOpen.System.Diagnostics.Loggers.IBdoLogger
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Application.Services.ITBdoServiceOptions`2.Loggers
  commentId: P:BindOpen.Application.Services.ITBdoServiceOptions`2.Loggers
  isExternal: true
  name: Loggers
  nameWithType: ITBdoServiceOptions<SServ, SHost>.Loggers
  fullName: BindOpen.Application.Services.ITBdoServiceOptions<SServ, SHost>.Loggers
  nameWithType.vb: ITBdoServiceOptions(Of SServ, SHost).Loggers
  fullName.vb: BindOpen.Application.Services.ITBdoServiceOptions(Of SServ, SHost).Loggers
- uid: System.Collections.Generic.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: System.Collections.Generic.List<>
  nameWithType.vb: List(Of )
  fullName.vb: System.Collections.Generic.List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Application.Services.TBdoServiceOptions`2.FuncSettingsConverter*
  commentId: Overload:BindOpen.Application.Services.TBdoServiceOptions`2.FuncSettingsConverter
  isExternal: true
  name: FuncSettingsConverter
  nameWithType: TBdoServiceOptions<SServ, SHost>.FuncSettingsConverter
  fullName: BindOpen.Application.Services.TBdoServiceOptions<SServ, SHost>.FuncSettingsConverter
  nameWithType.vb: TBdoServiceOptions(Of SServ, SHost).FuncSettingsConverter
  fullName.vb: BindOpen.Application.Services.TBdoServiceOptions(Of SServ, SHost).FuncSettingsConverter
- uid: BindOpen.Application.Services.ITBdoServiceOptions{{SServ},{SHost}}.FuncSettingsConverter
  commentId: P:BindOpen.Application.Services.ITBdoServiceOptions{`0,`1}.FuncSettingsConverter
  parent: BindOpen.Application.Services.ITBdoServiceOptions{{SServ},{SHost}}
  definition: BindOpen.Application.Services.ITBdoServiceOptions`2.FuncSettingsConverter
  name: FuncSettingsConverter
  nameWithType: ITBdoServiceOptions<SServ, SHost>.FuncSettingsConverter
  fullName: BindOpen.Application.Services.ITBdoServiceOptions<SServ, SHost>.FuncSettingsConverter
  nameWithType.vb: ITBdoServiceOptions(Of SServ, SHost).FuncSettingsConverter
  fullName.vb: BindOpen.Application.Services.ITBdoServiceOptions(Of SServ, SHost).FuncSettingsConverter
- uid: BindOpen.Application.Services.ITBdoServiceOptions`2.FuncSettingsConverter
  commentId: P:BindOpen.Application.Services.ITBdoServiceOptions`2.FuncSettingsConverter
  isExternal: true
  name: FuncSettingsConverter
  nameWithType: ITBdoServiceOptions<SServ, SHost>.FuncSettingsConverter
  fullName: BindOpen.Application.Services.ITBdoServiceOptions<SServ, SHost>.FuncSettingsConverter
  nameWithType.vb: ITBdoServiceOptions(Of SServ, SHost).FuncSettingsConverter
  fullName.vb: BindOpen.Application.Services.ITBdoServiceOptions(Of SServ, SHost).FuncSettingsConverter
shouldSkipMarkup: true
