### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  id: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.ConfigurationExtension
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
  type: Namespace
  assemblies:
  - BindOpen.Runtime.NetCore
references:
- uid: Microsoft.Extensions.Configuration.ConfigurationExtension
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationExtension
  isExternal: true
  name: ConfigurationExtension
  nameWithType: ConfigurationExtension
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtension
shouldSkipMarkup: true
