### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Entities
  commentId: N:BindOpen.Application.Entities
  id: BindOpen.Application.Entities
  children:
  - BindOpen.Application.Entities.ApplicationEntity
  - BindOpen.Application.Entities.ApplicationEntityScope
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Entities
  nameWithType: BindOpen.Application.Entities
  fullName: BindOpen.Application.Entities
  type: Namespace
  assemblies:
  - BindOpen.Core
references:
- uid: BindOpen.Application.Entities.ApplicationEntity
  commentId: T:BindOpen.Application.Entities.ApplicationEntity
  name: ApplicationEntity
  nameWithType: ApplicationEntity
  fullName: BindOpen.Application.Entities.ApplicationEntity
- uid: BindOpen.Application.Entities.ApplicationEntityScope
  commentId: T:BindOpen.Application.Entities.ApplicationEntityScope
  parent: BindOpen.Application.Entities
  name: ApplicationEntityScope
  nameWithType: ApplicationEntityScope
  fullName: BindOpen.Application.Entities.ApplicationEntityScope
- uid: BindOpen.Application.Entities
  commentId: N:BindOpen.Application.Entities
  name: BindOpen.Application.Entities
  nameWithType: BindOpen.Application.Entities
  fullName: BindOpen.Application.Entities
shouldSkipMarkup: true
