### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Scopes
  commentId: N:BindOpen.Application.Scopes
  id: BindOpen.Application.Scopes
  children:
  - BindOpen.Application.Scopes.BdoScopeExtension_DbConnectors
  - BindOpen.Application.Scopes.BdoScopeExtension_MSSqlServer
  - BindOpen.Application.Scopes.BdoScopeExtension_PostgreSql
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Scopes
  nameWithType: BindOpen.Application.Scopes
  fullName: BindOpen.Application.Scopes
  type: Namespace
  assemblies:
  - BindOpen.Databases
references:
- uid: BindOpen.Application.Scopes.BdoScopeExtension_DbConnectors
  commentId: T:BindOpen.Application.Scopes.BdoScopeExtension_DbConnectors
  name: BdoScopeExtension_DbConnectors
  nameWithType: BdoScopeExtension_DbConnectors
  fullName: BindOpen.Application.Scopes.BdoScopeExtension_DbConnectors
- uid: BindOpen.Application.Scopes.BdoScopeExtension_MSSqlServer
  commentId: T:BindOpen.Application.Scopes.BdoScopeExtension_MSSqlServer
  name: BdoScopeExtension_MSSqlServer
  nameWithType: BdoScopeExtension_MSSqlServer
  fullName: BindOpen.Application.Scopes.BdoScopeExtension_MSSqlServer
- uid: BindOpen.Application.Scopes.BdoScopeExtension_PostgreSql
  commentId: T:BindOpen.Application.Scopes.BdoScopeExtension_PostgreSql
  name: BdoScopeExtension_PostgreSql
  nameWithType: BdoScopeExtension_PostgreSql
  fullName: BindOpen.Application.Scopes.BdoScopeExtension_PostgreSql
shouldSkipMarkup: true
