### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Services
  commentId: N:BindOpen.Application.Services
  id: BindOpen.Application.Services
  children:
  - BindOpen.Application.Services.BdoDbService
  - BindOpen.Application.Services.BdoDbServiceFactory
  - BindOpen.Application.Services.IBdoDbService
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Services
  nameWithType: BindOpen.Application.Services
  fullName: BindOpen.Application.Services
  type: Namespace
  assemblies:
  - BindOpen.Databases
references:
- uid: BindOpen.Application.Services.BdoDbService
  commentId: T:BindOpen.Application.Services.BdoDbService
  name: BdoDbService
  nameWithType: BdoDbService
  fullName: BindOpen.Application.Services.BdoDbService
- uid: BindOpen.Application.Services.BdoDbServiceFactory
  commentId: T:BindOpen.Application.Services.BdoDbServiceFactory
  name: BdoDbServiceFactory
  nameWithType: BdoDbServiceFactory
  fullName: BindOpen.Application.Services.BdoDbServiceFactory
- uid: BindOpen.Application.Services.IBdoDbService
  commentId: T:BindOpen.Application.Services.IBdoDbService
  parent: BindOpen.Application.Services
  name: IBdoDbService
  nameWithType: IBdoDbService
  fullName: BindOpen.Application.Services.IBdoDbService
- uid: BindOpen.Application.Services
  commentId: N:BindOpen.Application.Services
  name: BindOpen.Application.Services
  nameWithType: BindOpen.Application.Services
  fullName: BindOpen.Application.Services
shouldSkipMarkup: true
