### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Exceptions
  commentId: N:BindOpen.Application.Exceptions
  id: BindOpen.Application.Exceptions
  children:
  - BindOpen.Application.Exceptions.BdoHostLoadException
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Exceptions
  nameWithType: BindOpen.Application.Exceptions
  fullName: BindOpen.Application.Exceptions
  type: Namespace
  assemblies:
  - BindOpen.Core
references:
- uid: BindOpen.Application.Exceptions.BdoHostLoadException
  commentId: T:BindOpen.Application.Exceptions.BdoHostLoadException
  name: BdoHostLoadException
  nameWithType: BdoHostLoadException
  fullName: BindOpen.Application.Exceptions.BdoHostLoadException
shouldSkipMarkup: true
