### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Settings
  commentId: N:BindOpen.Application.Settings
  id: BindOpen.Application.Settings
  children:
  - BindOpen.Application.Settings.BdoDefaultAppSettings
  - BindOpen.Application.Settings.BdoDefaultSettings
  - BindOpen.Application.Settings.BdoHostSettings
  - BindOpen.Application.Settings.IBdoAppSettings
  - BindOpen.Application.Settings.IBdoHostSettings
  - BindOpen.Application.Settings.IBdoSettings
  - BindOpen.Application.Settings.ITBdoSettings`1
  - BindOpen.Application.Settings.TBdoAppSettings`1
  - BindOpen.Application.Settings.TBdoSettings`1
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Settings
  nameWithType: BindOpen.Application.Settings
  fullName: BindOpen.Application.Settings
  type: Namespace
  assemblies:
  - BindOpen.Runtime
references:
- uid: BindOpen.Application.Settings.BdoDefaultAppSettings
  commentId: T:BindOpen.Application.Settings.BdoDefaultAppSettings
  name: BdoDefaultAppSettings
  nameWithType: BdoDefaultAppSettings
  fullName: BindOpen.Application.Settings.BdoDefaultAppSettings
- uid: BindOpen.Application.Settings.IBdoAppSettings
  commentId: T:BindOpen.Application.Settings.IBdoAppSettings
  parent: BindOpen.Application.Settings
  name: IBdoAppSettings
  nameWithType: IBdoAppSettings
  fullName: BindOpen.Application.Settings.IBdoAppSettings
- uid: BindOpen.Application.Settings.TBdoAppSettings`1
  commentId: T:BindOpen.Application.Settings.TBdoAppSettings`1
  name: TBdoAppSettings<Q>
  nameWithType: TBdoAppSettings<Q>
  fullName: BindOpen.Application.Settings.TBdoAppSettings<Q>
  nameWithType.vb: TBdoAppSettings(Of Q)
  fullName.vb: BindOpen.Application.Settings.TBdoAppSettings(Of Q)
  name.vb: TBdoAppSettings(Of Q)
  spec.csharp:
  - uid: BindOpen.Application.Settings.TBdoAppSettings`1
    name: TBdoAppSettings
    nameWithType: TBdoAppSettings
    fullName: BindOpen.Application.Settings.TBdoAppSettings
  - name: <
    nameWithType: <
    fullName: <
  - name: Q
    nameWithType: Q
    fullName: Q
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: BindOpen.Application.Settings.TBdoAppSettings`1
    name: TBdoAppSettings
    nameWithType: TBdoAppSettings
    fullName: BindOpen.Application.Settings.TBdoAppSettings
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: Q
    nameWithType: Q
    fullName: Q
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Application.Settings.BdoDefaultSettings
  commentId: T:BindOpen.Application.Settings.BdoDefaultSettings
  name: BdoDefaultSettings
  nameWithType: BdoDefaultSettings
  fullName: BindOpen.Application.Settings.BdoDefaultSettings
- uid: BindOpen.Application.Settings.BdoHostSettings
  commentId: T:BindOpen.Application.Settings.BdoHostSettings
  name: BdoHostSettings
  nameWithType: BdoHostSettings
  fullName: BindOpen.Application.Settings.BdoHostSettings
- uid: BindOpen.Application.Settings.IBdoHostSettings
  commentId: T:BindOpen.Application.Settings.IBdoHostSettings
  parent: BindOpen.Application.Settings
  name: IBdoHostSettings
  nameWithType: IBdoHostSettings
  fullName: BindOpen.Application.Settings.IBdoHostSettings
- uid: BindOpen.Application.Settings.IBdoSettings
  commentId: T:BindOpen.Application.Settings.IBdoSettings
  parent: BindOpen.Application.Settings
  name: IBdoSettings
  nameWithType: IBdoSettings
  fullName: BindOpen.Application.Settings.IBdoSettings
- uid: BindOpen.Application.Settings.ITBdoSettings`1
  commentId: T:BindOpen.Application.Settings.ITBdoSettings`1
  name: ITBdoSettings<Q>
  nameWithType: ITBdoSettings<Q>
  fullName: BindOpen.Application.Settings.ITBdoSettings<Q>
  nameWithType.vb: ITBdoSettings(Of Q)
  fullName.vb: BindOpen.Application.Settings.ITBdoSettings(Of Q)
  name.vb: ITBdoSettings(Of Q)
  spec.csharp:
  - uid: BindOpen.Application.Settings.ITBdoSettings`1
    name: ITBdoSettings
    nameWithType: ITBdoSettings
    fullName: BindOpen.Application.Settings.ITBdoSettings
  - name: <
    nameWithType: <
    fullName: <
  - name: Q
    nameWithType: Q
    fullName: Q
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: BindOpen.Application.Settings.ITBdoSettings`1
    name: ITBdoSettings
    nameWithType: ITBdoSettings
    fullName: BindOpen.Application.Settings.ITBdoSettings
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: Q
    nameWithType: Q
    fullName: Q
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Application.Settings.TBdoSettings`1
  commentId: T:BindOpen.Application.Settings.TBdoSettings`1
  name: TBdoSettings<Q>
  nameWithType: TBdoSettings<Q>
  fullName: BindOpen.Application.Settings.TBdoSettings<Q>
  nameWithType.vb: TBdoSettings(Of Q)
  fullName.vb: BindOpen.Application.Settings.TBdoSettings(Of Q)
  name.vb: TBdoSettings(Of Q)
  spec.csharp:
  - uid: BindOpen.Application.Settings.TBdoSettings`1
    name: TBdoSettings
    nameWithType: TBdoSettings
    fullName: BindOpen.Application.Settings.TBdoSettings
  - name: <
    nameWithType: <
    fullName: <
  - name: Q
    nameWithType: Q
    fullName: Q
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: BindOpen.Application.Settings.TBdoSettings`1
    name: TBdoSettings
    nameWithType: TBdoSettings
    fullName: BindOpen.Application.Settings.TBdoSettings
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: Q
    nameWithType: Q
    fullName: Q
  - name: )
    nameWithType: )
    fullName: )
- uid: BindOpen.Application.Settings
  commentId: N:BindOpen.Application.Settings
  name: BindOpen.Application.Settings
  nameWithType: BindOpen.Application.Settings
  fullName: BindOpen.Application.Settings
shouldSkipMarkup: true
