### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Configuration
  commentId: N:BindOpen.Application.Configuration
  id: BindOpen.Application.Configuration
  children:
  - BindOpen.Application.Configuration.BdoAppConfiguration
  - BindOpen.Application.Configuration.BdoBaseConfiguration
  - BindOpen.Application.Configuration.BdoConfigurationBundle
  - BindOpen.Application.Configuration.BdoHostConfiguration
  - BindOpen.Application.Configuration.BdoUsableConfiguration
  - BindOpen.Application.Configuration.ConfigurationFactory
  - BindOpen.Application.Configuration.IBdoAppConfiguration
  - BindOpen.Application.Configuration.IBdoBaseConfiguration
  - BindOpen.Application.Configuration.IBdoHostConfiguration
  - BindOpen.Application.Configuration.IBdoUsableConfigurationDto
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Configuration
  nameWithType: BindOpen.Application.Configuration
  fullName: BindOpen.Application.Configuration
  type: Namespace
  assemblies:
  - BindOpen.Core
references:
- uid: BindOpen.Application.Configuration.BdoBaseConfiguration
  commentId: T:BindOpen.Application.Configuration.BdoBaseConfiguration
  parent: BindOpen.Application.Configuration
  name: BdoBaseConfiguration
  nameWithType: BdoBaseConfiguration
  fullName: BindOpen.Application.Configuration.BdoBaseConfiguration
- uid: BindOpen.Application.Configuration.BdoConfigurationBundle
  commentId: T:BindOpen.Application.Configuration.BdoConfigurationBundle
  parent: BindOpen.Application.Configuration
  name: BdoConfigurationBundle
  nameWithType: BdoConfigurationBundle
  fullName: BindOpen.Application.Configuration.BdoConfigurationBundle
- uid: BindOpen.Application.Configuration.BdoUsableConfiguration
  commentId: T:BindOpen.Application.Configuration.BdoUsableConfiguration
  parent: BindOpen.Application.Configuration
  name: BdoUsableConfiguration
  nameWithType: BdoUsableConfiguration
  fullName: BindOpen.Application.Configuration.BdoUsableConfiguration
- uid: BindOpen.Application.Configuration.ConfigurationFactory
  commentId: T:BindOpen.Application.Configuration.ConfigurationFactory
  parent: BindOpen.Application.Configuration
  name: ConfigurationFactory
  nameWithType: ConfigurationFactory
  fullName: BindOpen.Application.Configuration.ConfigurationFactory
- uid: BindOpen.Application.Configuration.IBdoBaseConfiguration
  commentId: T:BindOpen.Application.Configuration.IBdoBaseConfiguration
  parent: BindOpen.Application.Configuration
  name: IBdoBaseConfiguration
  nameWithType: IBdoBaseConfiguration
  fullName: BindOpen.Application.Configuration.IBdoBaseConfiguration
- uid: BindOpen.Application.Configuration.IBdoUsableConfigurationDto
  commentId: T:BindOpen.Application.Configuration.IBdoUsableConfigurationDto
  parent: BindOpen.Application.Configuration
  name: IBdoUsableConfigurationDto
  nameWithType: IBdoUsableConfigurationDto
  fullName: BindOpen.Application.Configuration.IBdoUsableConfigurationDto
- uid: BindOpen.Application.Configuration.BdoAppConfiguration
  commentId: T:BindOpen.Application.Configuration.BdoAppConfiguration
  name: BdoAppConfiguration
  nameWithType: BdoAppConfiguration
  fullName: BindOpen.Application.Configuration.BdoAppConfiguration
- uid: BindOpen.Application.Configuration.BdoHostConfiguration
  commentId: T:BindOpen.Application.Configuration.BdoHostConfiguration
  parent: BindOpen.Application.Configuration
  name: BdoHostConfiguration
  nameWithType: BdoHostConfiguration
  fullName: BindOpen.Application.Configuration.BdoHostConfiguration
- uid: BindOpen.Application.Configuration.IBdoAppConfiguration
  commentId: T:BindOpen.Application.Configuration.IBdoAppConfiguration
  parent: BindOpen.Application.Configuration
  name: IBdoAppConfiguration
  nameWithType: IBdoAppConfiguration
  fullName: BindOpen.Application.Configuration.IBdoAppConfiguration
- uid: BindOpen.Application.Configuration.IBdoHostConfiguration
  commentId: T:BindOpen.Application.Configuration.IBdoHostConfiguration
  parent: BindOpen.Application.Configuration
  name: IBdoHostConfiguration
  nameWithType: IBdoHostConfiguration
  fullName: BindOpen.Application.Configuration.IBdoHostConfiguration
- uid: BindOpen.Application.Configuration
  commentId: N:BindOpen.Application.Configuration
  name: BindOpen.Application.Configuration
  nameWithType: BindOpen.Application.Configuration
  fullName: BindOpen.Application.Configuration
shouldSkipMarkup: true
